const words = [
  { "en": "bought (e)", "nl": "kocht" },
  { "en": "sat (m)", "nl": "zaten" },
  { "en": "have sat", "nl": "heeft gezeten" },
  { "en": "have departed", "nl": "heeft vertrokken" },
  { "en": "may (onverleden, e)", "nl": "mag" },
  { "en": "may (verleden, e)", "nl": "mocht" },
  { "en": "have may", "nl": "heeft gemogen" },
  { "en": "had (e)", "nl": "had" },
  { "en": "to depend", "nl": "afhangen" },
  { "en": "depend (e)", "nl": "hang af" },
  { "en": "depended (e)", "nl": "hing af" },
  { "en": "spoke (e)", "nl": "sprak" },
  { "en": "chose (e)", "nl": "koos" },
  { "en": "cycled (e)", "nl": "fietst" },
  { "en": "brought (e)", "nl": "bracht" },
  { "en": "has moved house", "nl": "is verhuisd" },
  { "en": "has shone", "nl": "heeft geschenen" },
  { "en": "melted (e)", "nl": "smolt" },
  { "en": "died (e)", "nl": "stierf" },
  { "en": "has died", "nl": "heeft gestorven" },
  { "en": "have hanged", "nl": "heeft gehangen" },
  { "en": "took (e)", "nl": "nam" },
  { "en": "have taken", "nl": "genomen" },
  { "en": "played (e)", "nl": "speelde" },
  { "en": "spoke (m)", "nl": "spraken" },
  { "en": "frozen (e)", "nl": "vroor" },
  { "en": "to sound", "nl": "klinken" },
  { "en": "to regret", "nl": "spijten" },
  { "en": "have ridden", "nl": "is gereden" },
  { "en": "to swim", "nl": "zwemmen" },
  { "en": "swam (e)", "nl": "zwom" },
  { "en": "has began", "nl": "is begonnen" },
  { "en": "to separate (divide)", "nl": "scheiden" },
  { "en": "separated (divided, e)", "nl": "scheidde" },
  { "en": "depend (m)", "nl": "hangt af" },
  { "en": "depended (m)", "nl": "hingen af" },
  { "en": "have depended", "nl": "heeft afgehangen" },
  { "en": "recieved (e)", "nl": "ontving" },
  { "en": "have recieved", "nl": "heeft ontvangen" },
  { "en": "held (loved, e)", "nl": "hield" },
  { "en": "have held (loved)", "nl": "heeft gehouden" },
  { "en": "understood (e)", "nl": "begreep" },
  { "en": "have eaten", "nl": "heeft gegeten" },
  { "en": "stand (e)", "nl": "sta" },
  { "en": "stood (e)", "nl": "stond" },
  { "en": "have stood", "nl": "heeft gestaan" },
  { "en": "became (e)", "nl": "werd" },
  { "en": "have become", "nl": "is geworden" },
  { "en": "want (m)", "nl": "wil / wilt wil" },
  { "en": "wanted (e)", "nl": "wilde / wou" },
  { "en": "wanted (m)", "nl": "wilden" },
  { "en": "have wanted", "nl": "heeft gewild" },
  { "en": "closed (e)", "nl": "dichtte" },
  { "en": "are (m)", "nl": "bent is" },
  { "en": "was (e)", "nl": "was" },
  { "en": "was (m)", "nl": "waren" },
  { "en": "have been", "nl": "is geweest" },
  { "en": "have walked", "nl": "heeft gelopen" },
  { "en": "had (e)", "nl": "had" },
  { "en": "to appear (to turn out)", "nl": "blijken" },
  { "en": "worked (e)", "nl": "werkte" },
  { "en": "have laid down", "nl": "heeft geleden" },
  { "en": "to fall", "nl": "vallen" },
  { "en": "have fallen", "nl": "heeft gevallen" },
  { "en": "worn (carried)", "nl": "droeg" },
  { "en": "have worn (have carried)", "nl": "heeft gedragen" },
  { "en": "to point out (to show)", "nl": "wijzen" },
  { "en": "point (e)", "nl": "wees" },
  { "en": "point (m)", "nl": "wijst" },
  { "en": "pointed (e)", "nl": "wees" },
  { "en": "stolen (e)", "nl": "stal" },
  { "en": "stolen (m)", "nl": "stalen" },
  { "en": "have stolen", "nl": "gestolen" },
  { "en": "to weigh", "nl": "wegen" },
  { "en": "shall (will)", "nl": "zullen" },
  { "en": "shall (e)", "nl": "zal" },
  { "en": "should (e)", "nl": "zou" },
  { "en": "", "nl": "" },
  { "en": "", "nl": "" },
  { "en": "", "nl": "" },
]