const words = [
  { "en": "gave (m)", "nl": "gaf" },
  { "en": "move (physically, e)", "nl": "beweeg" },
  { "en": "moved (physically, m)", "nl": "bewoog" },
  { "en": "has moved (physically)", "nl": "heeft bewogen" },
  { "en": "shall (will, m)", "nl": "zal / zult" },
  { "en": "has taken", "nl": "heeft genomen" },
  { "en": "baked (e)", "nl": "bakte" },
  { "en": "has baked", "nl": "heeft gebakken" },
  { "en": "knew (e)", "nl": "wist" },
  { "en": "knew (m)", "nl": "wisten" },
  { "en": "has known", "nl": "heeft geweten" },
  { "en": "have known", "nl": "hebben geweten" },
  { "en": "slept (e)", "nl": "sliep" },
  { "en": "slept (m)", "nl": "sliepen" },
  { "en": "have slept", "nl": "hebben geslapen" },
  { "en": "can (e)", "nl": "kan" },
  { "en": "can (m)", "nl": "kan / kunt" },
  { "en": "could (e)", "nl": "kon" },
  { "en": "has been possible", "nl": "heeft gekund" },
  { "en": "has fallen", "nl": "is gevallen" },
  { "en": "done (e)", "nl": "deed" },
  { "en": "has done", "nl": "heeft gedaan" },
  { "en": "has opened", "nl": "heeft geopend" },
  { "en": "flew (e)", "nl": "vloog" },
  { "en": "flew (m)", "nl": "vlogen" },
  { "en": "has flown", "nl": "heeft/is gevlogen" },
  { "en": "study (e)", "nl": "studeer" },
  { "en": "rode (e)", "nl": "reed" },
  { "en": "has ridden", "nl": "heeft/is gereden" },
  { "en": "weighed (e)", "nl": "woog" },
  { "en": "have weighed", "nl": "hebben gewogen" },
  { "en": "cycle (m)", "nl": "fietst" },
  { "en": "cycled (e)", "nl": "fietste" },
  { "en": "have separated (divided)", "nl": "hebben gescheiden" },
  { "en": "has worn (carried)", "nl": "heeft gedragen" },
  { "en": "washed (e)", "nl": "waste" },
  { "en": "have washed", "nl": "heeft gewassen" },
  { "en": "has swam", "nl": "heeft/is gezwommen" },
  { "en": "forgot (e)", "nl": "vergat" },
  { "en": "forgot (m)", "nl": "vergaten" },
  { "en": "has forgotten", "nl": "heeft/is vergeten" },
  { "en": "may (e)", "nl": "mag" },
  { "en": "may (m)", "nl": "mag / moogt" },
  { "en": "might (e)", "nl": "mocht" },
  { "en": "want (m)", "nl": "wil / wilt" },
  { "en": "have appeared (turned out)", "nl": "zijn gebleken" },
  { "en": "to exist", "nl": "bestaan" },
  { "en": "exist (e)", "nl": "besta" },
  { "en": "exist (m)", "nl": "bestaat" },
  { "en": "existed (e)", "nl": "bestond" },
  { "en": "have existed", "nl": "hebben bestaan" },
  { "en": "sailed (e)", "nl": "voer" },
  { "en": "has sailed", "nl": "heeft/is gevaren" },
  { "en": "had to (e)", "nl": "moest" },
  { "en": "have had to", "nl": "hebben gemoeten" },
  { "en": "searched (e)", "nl": "zocht" },
  { "en": "has searched", "nl": "heeft gezocht" },
  { "en": "has melted", "nl": "is gesmolten" },
  { "en": "became (e)", "nl": "werd" },
  { "en": "has become", "nl": "is geworden" },
  { "en": "has moved house", "nl": "is verhuisd" },
  { "en": "moved house (m)", "nl": "verhuisden" },
  { "en": "gone (e)", "nl": "ging" },
  { "en": "has gone", "nl": "is gegaan" },
  { "en": "learnt (e)", "nl": "leerde" },
  { "en": "learnt (m)", "nl": "leerden" },
  { "en": "have frozen", "nl": "hebben gevroren" },
  { "en": "sounded (e)", "nl": "klonk" },
  { "en": "has sounded", "nl": "heeft geklonken" },
  { "en": "have worked", "nl": "hebben gewerkt" },
  { "en": "to offer (command)", "nl": "bieden" },
  { "en": "has offered (command)", "nl": "heeft geboden" },
  { "en": "ate (e)", "nl": "at" },
  { "en": "ate (m)", "nl": "aten" },
  { "en": "to be called (named)", "nl": "heten" },
  { "en": "called (named, e)", "nl": "heette)" },
  { "en": "have called", "nl": "hebben geheten" },
  { "en": "has died", "nl": "is gestorven" },
  { "en": "drink (e)", "nl": "drink" },
  { "en": "drank (e)", "nl": "dronk" },
  { "en": "have drunk", "nl": "hebben gedronken" },
  { "en": "saw (e)", "nl": "zag" },
  { "en": "have seen", "nl": "hebben gezien" },
  { "en": "seems (m)", "nl": "lijkt" },
  { "en": "seemed (m)", "nl": "leken" },
  { "en": "has seemed", "nl": "heeft geleken" },
  { "en": "has begun", "nl": "is begonnen" },
  { "en": "stand (m)", "nl": "staat" },
  { "en": "has stood", "nl": "heeft gestaan" },
  { "en": "laid (down)", "nl": "lag" },
  { "en": "have laid down", "nl": "hebben gelegen" },
  { "en": "have cooked", "nl": "hebben gekookt" },
  { "en": "have recieved", "nl": "hebben ontvangen" },
  { "en": "closed (shut, e)", "nl": "dichtte" },
  { "en": "have closed", "nl": "hebben gedicht" },
  { "en": "spited (m)", "nl": "speten" },
  { "en": "have spited", "nl": "hebben gespeten" },
  { "en": "have understood", "nl": "hebben begrepen" },
  { "en": "read (verleden, e)", "nl": "las" },
  { "en": "read (verleden, m)", "nl": "lazen" },
  { "en": "has read", "nl": "heeft gelezen" },
  { "en": "has looked (watched)", "nl": "heeft gekeken" },
  { "en": "travelled (e)", "nl": "reisde" },
  { "en": "have travelled", "nl": "hebben gereisd" },
  { "en": "laughed (e)", "nl": "lachte" },
  { "en": "have laughed", "nl": "hebben gelachen" },
  { "en": "played (e)", "nl": "speelde" },
  { "en": "lived (reside, e)", "nl": "woonde" },
  { "en": "held (loved, e)", "nl": "hield" },
  { "en": "have loved", "nl": "hebben gehouden" },
  { "en": "has written", "nl": "heeft geschreven" },
  { "en": "to come", "nl": "komen" },
  { "en": "come (e)", "nl": "kom" },
  { "en": "came (e)", "nl": "kwam" },
  { "en": "came (m)", "nl": "kwamen" },
  { "en": "has come", "nl": "is gekomen" },
  { "en": "have brought", "nl": "hebben gebracht" },
  { "en": "enjoyed (e)", "nl": "genoot" },
  { "en": "enjoyed (m)", "nl": "genoten" },
  { "en": "have enjoyed", "nl": "hebbem genoten" },
  { "en": "sung (e)", "nl": "zong" },
  { "en": "have sung", "nl": "hebben gezongen" },
  { "en": "to clean", "nl": "schoonmaken" },
  { "en": "clean (e)", "nl": "maak schoon" },
  { "en": "clean (m)", "nl": "maakt schoon" },
  { "en": "cleaned (e)", "nl": "maakte schoon" },
  { "en": "cleaned (m)", "nl": "maakten schoon" },
  { "en": "have cleaned", "nl": "hebben schoongemaakt" },
  { "en": "helped (e)", "nl": "hielp" },
  { "en": "has helped", "nl": "heeft gehelpen" },
  { "en": "said (e)", "nl": "zeiden" },
  { "en": "has said", "nl": "heeft gezegd" },
  { "en": "listened (e)", "nl": "luisterde" },
  { "en": "guessed (advised, e)", "nl": "raadde" },
  { "en": "guessed (advised, m)", "nl": "raadden" },
  { "en": "has guessed (has advised)", "nl": "heeft geraden" },
  { "en": "are (m)", "nl": "bent is" },
  { "en": "was (e)", "nl": "was" },
  { "en": "was (m)", "nl": "waren" },
  { "en": "have been", "nl": "zijn geweest" },
  { "en": "talked (e)", "nl": "praatte" },
  { "en": "talked (m)", "nl": "praatten" },
  { "en": "have talked", "nl": "hebben gepraat" },
  { "en": "has gotten (received)", "nl": "heeft gekregen" },
  { "en": "have (m)", "nl": "hebt / heeft" },
  { "en": "had (e)", "nl": "had" },
  { "en": "had (m)", "nl": "hadden" },
  { "en": "has had", "nl": "heeft gehad" },
  { "en": "has asked", "nl": "heeft gevraagd" },
  { "en": "has left (departed)", "nl": "is vertrokken" },
  { "en": "spoke (m)", "nl": "spraken" },
  { "en": "has spoken", "nl": "heeft gesproken" },
  { "en": "points out (m)", "nl": "wijst" },
]