const words = [
  { "en": "gave (e)", "nl": "gaf" },
  { "en": "gave (m)", "nl": "gaven" },
  { "en": "move (physically, e)", "nl": "beweeg" },
  { "en": "moved (physically, e)", "nl": "bewoog" },
  { "en": "has moved (physically)", "nl": "heeft bewogen" },
  { "en": "shall (will, m)", "nl": "zal / zult" },
  { "en": "has taken", "nl": "heeft genomen" },
  { "en": "baked (e)", "nl": "bakte" },
  { "en": "has baked", "nl": "heeft gebakken" },
  { "en": "knew (e)", "nl": "wist" },
  { "en": "knew (m)", "nl": "wisten" },
  { "en": "have known", "nl": "hebben geweten" },
  { "en": "have slept", "nl": "hebben geslapen" },
  { "en": "can (m)", "nl": "kan / kunt" },
  { "en": "could (e)", "nl": "kon" },
  { "en": "has been possible", "nl": "heeft gekund" },
  { "en": "has fallen", "nl": "is gevallen" },
  { "en": "done (e)", "nl": "deed" },
  { "en": "has done", "nl": "heeft gedaan" },
  { "en": "flew (e)", "nl": "vloog" },
  { "en": "has flown", "nl": "heeft/is gevlogen" },
  { "en": "rode (e)", "nl": "reed" },
  { "en": "has ridden", "nl": "heeft/is gereden" },
  { "en": "weighed (e)", "nl": "woog" },
  { "en": "have weighed", "nl": "hebben gewogen" },
  { "en": "have separated (divided)", "nl": "hebben gescheiden" },
  { "en": "washed (e)", "nl": "waste" },
  { "en": "has swam", "nl": "heeft/is gezwommen" },
  { "en": "forgot (m)", "nl": "vergaten" },
  { "en": "has forgotten", "nl": "heeft/is vergeten" },
  { "en": "may (m)", "nl": "mag / moogt" },
  { "en": "want (m)", "nl": "wil / wilt" },
  { "en": "have appeared (turned out)", "nl": "zijn gebleken" },
  { "en": "exist (e)", "nl": "besta" },
  { "en": "exist (m)", "nl": "bestaat" },
  { "en": "existed (e)", "nl": "bestond" },
  { "en": "have existed", "nl": "hebben bestaan" },
  { "en": "has sailed", "nl": "heeft/is gevaren" },
  { "en": "have had to", "nl": "hebben gemoeten" },
  { "en": "searched (e)", "nl": "zocht" },
  { "en": "has searched", "nl": "heeft gezocht" },
  { "en": "became (e)", "nl": "werd" },
  { "en": "has become", "nl": "is geworden" },
  { "en": "gone (e)", "nl": "ging" },
  { "en": "has gone", "nl": "is gegaan" },
  { "en": "learnt (e)", "nl": "leerde" },
  { "en": "learnt (m)", "nl": "leerden" },
  { "en": "have frozen", "nl": "hebben gevroren" },
  { "en": "has sounded", "nl": "heeft geklonken" },
  { "en": "have worked", "nl": "hebben gewerkt" },
  { "en": "has offered (command)", "nl": "heeft geboden" },
  { "en": "ate (e)", "nl": "at" },
  { "en": "ate (m)", "nl": "aten" },
  { "en": "have called", "nl": "hebben geheten" },
  { "en": "have drunk", "nl": "hebben gedronken" },
  { "en": "have seen", "nl": "hebben gezien" },
  { "en": "seems (m)", "nl": "lijkt" },
  { "en": "has begun", "nl": "is begonnen" },
  { "en": "stand (m)", "nl": "staat" },
  { "en": "has stood", "nl": "heeft gestaan" },
  { "en": "lay (m)", "nl": "lag / legt"},
  { "en": "have laid down", "nl": "hebben gelegd" },
  { "en": "have recieved", "nl": "hebben ontvangen" },
  { "en": "have closed", "nl": "hebben gedicht" },
  { "en": "have understood", "nl": "hebben begrepen" },
  { "en": "has read", "nl": "heeft gelezen" },
  { "en": "has looked (watched)", "nl": "heeft gekeken" },
  { "en": "travelled (e)", "nl": "reisde" },
  { "en": "have travelled", "nl": "hebben gereisd" },
  { "en": "laughed (e)", "nl": "lachte" },
  { "en": "have laughed", "nl": "hebben gelachen" },
  { "en": "lived (reside, e)", "nl": "woonde" },
  { "en": "to come", "nl": "komen" },
  { "en": "has come", "nl": "is gekomen" },
  { "en": "enjoyed (e)", "nl": "genoot" },
  { "en": "have enjoyed", "nl": "hebben genoten" },
  { "en": "have sung", "nl": "hebben gezongen" },
  { "en": "said (e)", "nl": "zeiden" },
  { "en": "has said", "nl": "heeft gezegd" },
  { "en": "listened (e)", "nl": "luisterde" },
  { "en": "has guessed (has advised)", "nl": "heeft geraden" },
  { "en": "are (m)", "nl": "bent is" },
  { "en": "was (m)", "nl": "waren" },
  { "en": "have been", "nl": "zijn geweest" },
  { "en": "talked (e)", "nl": "praatte" },
  { "en": "have talked", "nl": "hebben gepraat" },
  { "en": "has gotten (received)", "nl": "heeft gekregen" },
  { "en": "have (m)", "nl": "hebt / heeft" },
  { "en": "had (m)", "nl": "hadden" },
  { "en": "has had", "nl": "heeft gehad" },
  { "en": "has asked", "nl": "heeft gevraagd" },
  { "en": "has left (departed)", "nl": "is vertrokken" },
  { "en": "spoke (m)", "nl": "spraken" },
  { "en": "has spoken", "nl": "heeft gesproken" },
  { "en": "points out (m)", "nl": "wijst" },
]