const words = [
  { "en": "continual", "nl": "voortdurend" },
  { "en": "flung", "nl": "geslingerd" },
  { "en": "evidently (apparently)", "nl": "blijkbaar" },
  { "en": "meanwhile", "nl": "ondertussen" },
  { "en": "disturbed", "nl": "verstoord" },
  { "en": "rather (quite)", "nl": "nogal" },
  { "en": "let me introduce myself", "nl": "even voorstellen" },
  { "en": "suggested (proposed)", "nl": "voorgesteld" },
  { "en": "suggestion", "nl": "voorstel (suggestie)" },
  { "en": "suggestions (plural)", "nl": "voorstellen (suggesties)" },
  { "en": "proposal", "nl": "voorstel (plan)" },
  { "en": "proposals (plural)", "nl": "voorstellen (plannen)" },
  { "en": "presumably", "nl": "vermoedelijk" },
  { "en": "suspected (past tense)", "nl": "vermoedde" },
  { "en": "suspected (participle/adjective)", "nl": "vermoed" },
  { "en": "permission", "nl": "toestemming" },
  { "en": "example", "nl": "voorbeeld" },
  { "en": "examples (plural)", "nl": "voorbeelden" },
  { "en": "fetched", "nl": "haalde" },
  { "en": "cheerful", "nl": "opgewekt" },
  { "en": "called", "nl": "geroepen" },
  { "en": "blazed", "nl": "laaiden" },
  { "en": "brave", "nl": "moedig" },
  { "en": "male cousin", "nl": "neef (familielid)" },
  { "en": "male cousins (plural)", "nl": "neven (familieleden)" },
  { "en": "nephew", "nl": "neef (oomzegger)" },
  { "en": "nephews (plural)", "nl": "neven (oomzeggers)" },
  { "en": "once", "nl": "eenmaal" },
  { "en": "chewing", "nl": "kauwen" },
  { "en": "icy", "nl": "ijzig" },
  { "en": "extremely", "nl": "uiterst" },
  { "en": "words", "nl": "woorden" },
  { "en": "since (because)", "nl": "aangezien" },
  { "en": "saved", "nl": "gered" },
  { "en": "concealed oneself", "nl": "verschool zich" },
  { "en": "organised (arranged)", "nl": "geregeld (georganiseerd)" },
  { "en": "regular", "nl": "geregeld (regelmatig)" },
  { "en": "connected", "nl": "aangesloten (verbonden)" },
  { "en": "affiliated", "nl": "aangesloten (lid)" },
  { "en": "conclusion (decision)", "nl": "besluit" },
  { "en": "conclusions (plural)", "nl": "besluiten" },
  { "en": "excluded (past singular)", "nl": "sloot uit" },
  { "en": "excluded (participle)", "nl": "uitgesloten" },
  { "en": "destroyed", "nl": "verwoest" },
  { "en": "traffic", "nl": "verkeer" },
  { "en": "carries", "nl": "draagt (torsen)" },
  { "en": "wears", "nl": "draagt (aanhebben)" },
  { "en": "carried (past singular)", "nl": "droeg (torsen)" },
  { "en": "carried (participle)", "nl": "gedragen (torsen)" },
  { "en": "wore (past singular)", "nl": "droeg (aanhebben)" },
  { "en": "worn (participle)", "nl": "gedragen (aanhebben)" },
  { "en": "behaved (past singular)", "nl": "gedroeg zich" },
  { "en": "behaved (participle)", "nl": "zich gedragen (gedrag)" },
  { "en": "dressed", "nl": "gekleed" },
  { "en": "forward (bent forward)", "nl": "voorover" },
  { "en": "bow (arc)", "nl": "boog" },
  { "en": "bows (arcs - plural)", "nl": "bogen" },
  { "en": "collided", "nl": "botste" },
  { "en": "virtually", "nl": "vrijwel" },
  { "en": "tendency", "nl": "neiging" },
  { "en": "tendencies (plural)", "nl": "neigingen" },
  { "en": "fighting", "nl": "vechtend" },
  { "en": "approved", "nl": "goedgekeurd" },
  { "en": "intruders", "nl": "indringers" },
  { "en": "ostentatious", "nl": "opzichtig" },
  { "en": "attitude", "nl": "houding" },
  { "en": "attitudes (plural)", "nl": "houdingen" },
  { "en": "regarding", "nl": "wat betreft" },
  { "en": "entertained", "nl": "vermaakte" },
  { "en": "survived", "nl": "overleefde" },
  { "en": "disputed (doubted)", "nl": "betwijfelde" },
  { "en": "expired", "nl": "vervallen (verlopen)" },
  { "en": "dilapidated", "nl": "vervallen (bouwvallig)" },
  { "en": "lapsed", "nl": "vervallen (ongeldig)" },
  { "en": "damp", "nl": "vochtig" },
  { "en": "beautiful", "nl": "fraai" },
  { "en": "were missing", "nl": "ontbraken" },
  { "en": "missing", "nl": "ontbrekend" },
  { "en": "timbered (built)", "nl": "getimmerd" },
  { "en": "approached", "nl": "naderde" },
  { "en": "curved (bent)", "nl": "gebogen" },
  { "en": "amount", "nl": "hoeveelheid" },
  { "en": "amounts (plural)", "nl": "hoeveelheden" },
  { "en": "a few (some)", "nl": "enkele" },
  { "en": "patient", "nl": "geduldig" },
  { "en": "uncontrolled", "nl": "onbeheerst" },
  { "en": "controlled", "nl": "beheerst (kalm)" },
  { "en": "mastered", "nl": "beheerst (onder de knie)" },
  { "en": "gust", "nl": "vlaag" },
  { "en": "gusts (plural)", "nl": "vlagen" },
  { "en": "dropped", "nl": "zakte (daalde)" },
  { "en": "sank", "nl": "zakte (zonk)" },
  { "en": "dropped/sunk (participle)", "nl": "gezakt" },
  { "en": "pocket (bag)", "nl": "zak" },
  { "en": "pockets (bags - plural)", "nl": "zakken" },
  { "en": "business (matters/ affairs)", "nl": "zaken" },
  { "en": "completely", "nl": "volkomen" },
  { "en": "to appear", "nl": "verschijnen" },
  { "en": "appeared (past singular)", "nl": "verscheen" },
  { "en": "appeared (participle)", "nl": "verschenen" },
  { "en": "into view", "nl": "tevoorschijn" },
  { "en": "accident", "nl": "onval (ongeluk)" },
  { "en": "accidents (plural)", "nl": "onvallen (ongelukken)" },
  { "en": "as a result of which", "nl": "waardoor" },
  { "en": "grown (cultivated)", "nl": "gekweekt" },
  { "en": "complaints", "nl": "klachten" },
  { "en": "abuses (misconducts)", "nl": "misstanden" },
  { "en": "case (situation)", "nl": "geval" },
  { "en": "cases (situations - plural)", "nl": "gevallen" },
  { "en": "part", "nl": "gedeelte" },
  { "en": "parts (plural)", "nl": "gedeelten (gedeeltes)" },
  { "en": "examined", "nl": "bekeken (onderzocht)" },
  { "en": "viewed (past singular)", "nl": "bekeek" },
  { "en": "saw (past singular)", "nl": "zag" },
  { "en": "seen (participle)", "nl": "gezien" },
  { "en": "down", "nl": "neer" },
  { "en": "similar", "nl": "soortgelijk" },
  { "en": "enemy", "nl": "vijand" },
  { "en": "enemies (plural)", "nl": "vijanden" },
  { "en": "reached", "nl": "bereikte (kwam bij)" },
  { "en": "achieved", "nl": "bereikte (behaalde)" },
  { "en": "expectation", "nl": "verwachting" },
  { "en": "expectations (plural)", "nl": "verwachtingen" },
  { "en": "prepared", "nl": "bereid (klaar)" },
  { "en": "willing", "nl": "bereid (gewillig)" },
  { "en": "invitation", "nl": "uitnodiging" },
  { "en": "invitations (plural)", "nl": "uitnodigingen" },
  { "en": "matched (corresponding)", "nl": "overeenkomend" },
  { "en": "shallow", "nl": "oppervlakkig (ondiep)" },
  { "en": "superficial", "nl": "oppervlakkig (vluchtig)" },
  { "en": "deduction", "nl": "aftrek" },
  { "en": "compared", "nl": "vergeleken" },
  { "en": "literal", "nl": "letterlijk" },
  { "en": "actually", "nl": "eigenlijk" },
  { "en": "weight", "nl": "gewicht" },
  { "en": "weights (plural)", "nl": "gewichten" },
  { "en": "owed", "nl": "verschuldigd" },
  { "en": "support", "nl": "steun" },
  { "en": "recoiled", "nl": "deinsde" },
  { "en": "insult", "nl": "belediging" },
  { "en": "insults (plural)", "nl": "beledigingen" },
  { "en": "understood (interpreted)", "nl": "opgevat" },
  { "en": "displayed (represented)", "nl": "weergegeven" },
  { "en": "display (show)", "nl": "vertoon" },
  { "en": "banks (of a river)", "nl": "oevers" },
  { "en": "unobstructed", "nl": "ongehinderd" },
  { "en": "attempt", "nl": "poging" },
  { "en": "attempts (plural)", "nl": "pogingen" },
  { "en": "heard (past singular)", "nl": "hoorde" },
  { "en": "heard (participle)", "nl": "gehoord" },
  { "en": "obeyed (past singular)", "nl": "gehoorzaamde" },
  { "en": "obedient", "nl": "gehoorzaam" },
  { "en": "disobedient", "nl": "ongehoorzaam" },
  { "en": "thrown", "nl": "gegooid" },
  { "en": "grasped/understood (past singular)", "nl": "vatte" },
  { "en": "grasped/understood (participle)", "nl": "gevat" },
  { "en": "contained (past singular)", "nl": "bevatte" },
  { "en": "contained (participle)", "nl": "bevat" },
  { "en": "restored", "nl": "hersteld (gerepareerd)" },
  { "en": "recovered", "nl": "hersteld (genezen)" },
  { "en": "defence", "nl": "verdediging" },
  { "en": "defences (plural)", "nl": "verdedigingen" },
  { "en": "loss", "nl": "verlies" },
  { "en": "losses (plural)", "nl": "verliezen" },
  { "en": "submitted (presented)", "nl": "voorgelegd" },
  { "en": "disappeared", "nl": "verdwenen" },
  { "en": "cancelled", "nl": "afgelast" },
  { "en": "quite (fairly)", "nl": "behoorlijk (tamelijk)" },
  { "en": "properly", "nl": "behoorlijk (netjes)" },
  { "en": "inspired", "nl": "bezield" },
  { "en": "noticed", "nl": "opgevallen (bemerkt)" },
  { "en": "stood out", "nl": "opgevallen (uitgesprongen)" },
  { "en": "touches", "nl": "raakt (aanraakt)" },
  { "en": "hits", "nl": "raakt (treft)" },
  { "en": "becomes", "nl": "raakt (wordt)" },
  { "en": "when", "nl": "wanneer" },
  { "en": "emphasised", "nl": "benadrukt" },
]

