const words = [
{ "en": "finish (complete)", "nl": "afwerken" },
{ "en": "update (catch up on)", "nl": "bijwerken" },
{ "en": "continue working", "nl": "doorwerken" },
{ "en": "train (familiarise)", "nl": "inwerken" },
{ "en": "cooperate (participate)", "nl": "meewerken" },
{ "en": "have an after-effect", "nl": "nawerken" },
{ "en": "work overtime", "nl": "overwerken" },
{ "en": "collaborate", "nl": "samenwerken" },
{ "en": "obstruct (work against)", "nl": "tegenwerken" },
{ "en": "develop (work out)", "nl": "uitwerken" },
{ "en": "get rid of (work through)", "nl": "wegwerken" },
{ "en": "create (produce)", "nl": "aanmaken" },
{ "en": "finish", "nl": "afmaken" },
{ "en": "go through (experience)", "nl": "doormaken" },
{ "en": "make up for", "nl": "goedmaken" },
{ "en": "prepare (get ready)", "nl": "klaarmaken" },
{ "en": "loosen (detach)", "nl": "losmaken" },
{ "en": "experience", "nl": "meemaken" },
{ "en": "imitate (reproduce)", "nl": "namaken" },
{ "en": "use up (make up, prepare)", "nl": "opmaken" },
{ "en": "transfer money", "nl": "overmaken" },
{ "en": "clean", "nl": "schoonmaken" },
{ "en": "break", "nl": "stukmaken" },
{ "en": "matter (switch off, break up)", "nl": "uitmaken" },
{ "en": "fasten", "nl": "vastmaken" },
{ "en": "free (make available)", "nl": "vrijmaken" },
{ "en": "fulfil (prove true)", "nl": "waarmaken" },
{ "en": "remove", "nl": "wegmaken" },
{ "en": "attend", "nl": "bijwonen" },
{ "en": "live with someone", "nl": "inwonen" },
{ "en": "live together", "nl": "samenwonen" },
{ "en": "teach (acquire)", "nl": "aanleren" },
{ "en": "unlearn (break a habit)", "nl": "afleren" },
{ "en": "learn more", "nl": "bijleren" },
{ "en": "continue studying", "nl": "doorleren" },
{ "en": "play (take place)", "nl": "afspelen" },
{ "en": "keep playing (pass on)", "nl": "doorspelen" },
{ "en": "respond to (play in)", "nl": "inspelen" },
{ "en": "play along (take part)", "nl": "meespelen" },
{ "en": "reenact", "nl": "naspelen" },
{ "en": "flare up (act up)", "nl": "opspelen" },
{ "en": "transfer (dub)", "nl": "overspelen" },
{ "en": "play together", "nl": "samenspelen" },
{ "en": "play off (exploit)", "nl": "uitspelen" },
{ "en": "play for someone", "nl": "voorspelen" },
{ "en": "agree (arrange)", "nl": "afpraten" },
{ "en": "catch up", "nl": "bijpraten" },
{ "en": "keep talking", "nl": "doorpraten" },
{ "en": "join the discussion", "nl": "meepraten" },
{ "en": "talk afterwards (imitate)", "nl": "napraten" },
{ "en": "persuade", "nl": "ompraten" },
{ "en": "finish talking (talk out)", "nl": "uitpraten" },
{ "en": "eavesdrop (listen to)", "nl": "afluisteren" },
{ "en": "listen in", "nl": "meeluisteren" },
{ "en": "listen back", "nl": "terugluisteren" },
{ "en": "keep cycling", "nl": "doorfietsen" },
{ "en": "cycle along", "nl": "meefietsen" },
{ "en": "take a detour by bike", "nl": "omfietsen" },
{ "en": "cycle around", "nl": "rondfietsen" },
{ "en": "cycle back", "nl": "terugfietsen" },
{ "en": "cycle away", "nl": "wegfietsen" },
{ "en": "travel to (depart for)", "nl": "afreizen" },
{ "en": "travel on", "nl": "doorreizen" },
{ "en": "travel along", "nl": "meereizen" },
{ "en": "follow later", "nl": "nareizen" },
{ "en": "travel around", "nl": "rondreizen" },
{ "en": "travel back", "nl": "terugreizen" },
{ "en": "graduate", "nl": "afstuderen" },
{ "en": "continue studying", "nl": "doorstuderen" },
{ "en": "seal off", "nl": "afdichten" },
{ "en": "close (seal)", "nl": "dichtmaken" },
{ "en": "boil down (parboil)", "nl": "afkoken" },
{ "en": "continue boiling", "nl": "doorkoken" },
{ "en": "reduce by boiling", "nl": "inkoken" },
{ "en": "cook along", "nl": "meekoken" },
{ "en": "boil over", "nl": "overkoken" },
{ "en": "pre-cook", "nl": "voorkoken" },
{ "en": "move along with", "nl": "meeverhuizen" },
{ "en": "move back", "nl": "terugverhuizen" },
{ "en": "keep swimming (swim through)", "nl": "doorzwemmen" },
{ "en": "swim along", "nl": "meezwemmen" },
{ "en": "swim back", "nl": "terugzwemmen" },
{ "en": "swim away", "nl": "wegzwemmen" },
{ "en": "challenge (contest)", "nl": "aanvechten" },
{ "en": "keep fighting", "nl": "doorvechten" },
{ "en": "fight alongside", "nl": "meevechten" },
{ "en": "fight back", "nl": "terugvechten" },
{ "en": "fight out (settle)", "nl": "uitvechten" },
{ "en": "melt away", "nl": "afsmelten" },
{ "en": "merge (fuse)", "nl": "samensmelten" },
{ "en": "melt away", "nl": "wegsmelten" },
{ "en": "laugh along", "nl": "meelachen" },
{ "en": "smile at", "nl": "toelachen" },
{ "en": "laugh at", "nl": "uitlachen" },
{ "en": "laugh off", "nl": "weglachen" },
{ "en": "wash the dishes", "nl": "afwassen" },
{ "en": "wash out", "nl": "uitwassen" },
{ "en": "wash away", "nl": "wegwassen" },
{ "en": "finish baking", "nl": "afbakken" },
{ "en": "bake through", "nl": "doorbakken" },
{ "en": "bake along", "nl": "meebakken" },
{ "en": "fry up (reheat)", "nl": "opbakken" },
{ "en": "walk up to (incur)", "nl": "aanlopen" },
{ "en": "end (expire, walk down)", "nl": "aflopen" },
{ "en": "walk in (come in)", "nl": "binnenlopen" },
{ "en": "continue walking (go through)", "nl": "doorlopen" },
{ "en": "catch up (walk in)", "nl": "inlopen" },
{ "en": "walk along", "nl": "meelopen" },
{ "en": "miss out on (go wrong)", "nl": "mislopen" },
{ "en": "walk around (take a detour)", "nl": "omlopen" },
{ "en": "flood", "nl": "onderlopen" },
{ "en": "increase (sustain, walk up)", "nl": "oplopen" },
{ "en": "overflow (defect)", "nl": "overlopen" },
{ "en": "walk around", "nl": "rondlopen" },
{ "en": "coincide (converge)", "nl": "samenlopen" },
{ "en": "walk back (decrease)", "nl": "teruglopen" },
{ "en": "run over (end up, walk out)", "nl": "uitlopen" },
{ "en": "get stuck", "nl": "vastlopen" },
{ "en": "be ahead", "nl": "voorlopen" },
{ "en": "walk away (run away)", "nl": "weglopen" },
{ "en": "buy off (settle)", "nl": "afkopen" },
{ "en": "buy more", "nl": "bijkopen" },
{ "en": "purchase (buy in)", "nl": "inkopen" },
{ "en": "buy along", "nl": "meekopen" },
{ "en": "buy up", "nl": "opkopen" },
{ "en": "buy back", "nl": "terugkopen" },
{ "en": "buy out", "nl": "uitkopen" },
{ "en": "think through", "nl": "doordenken" },
{ "en": "think along (contribute ideas)", "nl": "meedenken" },
{ "en": "think about", "nl": "nadenken" },
{ "en": "reframe", "nl": "omdenken" },
{ "en": "think back", "nl": "terugdenken" },
{ "en": "think ahead", "nl": "vooruitdenken" },
{ "en": "apply (install, introduce)", "nl": "aanbrengen" },
{ "en": "dissuade (take off)", "nl": "afbrengen" },
{ "en": "teach (revive)", "nl": "bijbrengen" },
{ "en": "bring in", "nl": "binnenbrengen" },
{ "en": "spend time (bring through)", "nl": "doorbrengen" },
{ "en": "contribute (insert)", "nl": "inbrengen" },
{ "en": "bring along", "nl": "meebrengen" },
{ "en": "accommodate (place)", "nl": "onderbrengen" },
{ "en": "raise (yield, summon)", "nl": "opbrengen" },
{ "en": "transfer (convey)", "nl": "overbrengen" },
{ "en": "deliver around", "nl": "rondbrengen" },
{ "en": "bring together", "nl": "samenbrengen" },
{ "en": "bring back (reduce)", "nl": "terugbrengen" },
{ "en": "release (publish)", "nl": "uitbrengen" },
{ "en": "take away (bring somewhere)", "nl": "wegbrengen" },
{ "en": "search thoroughly", "nl": "afzoeken" },
{ "en": "search through", "nl": "doorzoeken" },
{ "en": "look up (visit)", "nl": "opzoeken" },
{ "en": "sort out (choose, investigate)", "nl": "uitzoeken" },
{ "en": "keep eating", "nl": "dooreten" },
{ "en": "eat along (join for a meal)", "nl": "mee-eten" },
{ "en": "eat up", "nl": "opeten" },
{ "en": "eat out", "nl": "uiteten" },
{ "en": "keep drinking", "nl": "doordrinken" },
{ "en": "drink beforehand", "nl": "indrinken" },
{ "en": "drink along", "nl": "meedrinken" },
{ "en": "drink up", "nl": "opdrinken" },
{ "en": "finish drinking", "nl": "uitdrinken" },
{ "en": "regard (watch)", "nl": "aanzien" },
{ "en": "refrain from (suffer)", "nl": "afzien" },
{ "en": "see through (understand)", "nl": "doorzien" },
{ "en": "realise (inspect)", "nl": "inzien" },
{ "en": "look back (care for)", "nl": "omzien" },
{ "en": "oversee (survey)", "nl": "overzien" },
{ "en": "see again", "nl": "terugzien" },
{ "en": "look out (look forward to, appear)", "nl": "uitzien" },
{ "en": "enter into (concern, switch on)", "nl": "aangaan" },
{ "en": "go off (fail, approach)", "nl": "afgaan" },
{ "en": "continue", "nl": "doorgaan" },
{ "en": "enter (take effect, address)", "nl": "ingaan" },
{ "en": "go along", "nl": "meegaan" },
{ "en": "deal with (socialise, go around)", "nl": "omgaan" },
{ "en": "undergo (set)", "nl": "ondergaan" },
{ "en": "rise (be absorbed, apply)", "nl": "opgaan" },
{ "en": "switch (pass, transfer)", "nl": "overgaan" },
{ "en": "go around", "nl": "rondgaan" },
{ "en": "go together (merge)", "nl": "samengaan" },
{ "en": "go back", "nl": "teruggaan" },
{ "en": "go out (assume)", "nl": "uitgaan" },
{ "en": "precede (lead)", "nl": "voorgaan" },
{ "en": "improve (move forward)", "nl": "vooruitgaan" },
{ "en": "leave", "nl": "weggaan" },
{ "en": "arrive (gain weight)", "nl": "aankomen" },
{ "en": "come off (approach)", "nl": "afkomen" },
{ "en": "come in (arrive)", "nl": "binnenkomen" },
{ "en": "get through (come through)", "nl": "doorkomen" },
{ "en": "come in (income)", "nl": "inkomen" },
{ "en": "come along", "nl": "meekomen" },
{ "en": "comply with (come later)", "nl": "nakomen" },
{ "en": "come down (amount to)", "nl": "neerkomen" },
{ "en": "die (perish)", "nl": "omkomen" },
{ "en": "arise (come up)", "nl": "opkomen" },
{ "en": "happen to (come across)", "nl": "overkomen" },
{ "en": "make ends meet", "nl": "rondkomen" },
{ "en": "come together", "nl": "samenkomen" },
{ "en": "encounter", "nl": "tegenkomen" },
{ "en": "come back", "nl": "terugkomen" },
{ "en": "intervene", "nl": "tussenkomen" },
{ "en": "come out (work out, be published)", "nl": "uitkomen" },
{ "en": "occur (prevent)", "nl": "voorkomen" },
{ "en": "make progress", "nl": "vooruitkomen" },
{ "en": "get away", "nl": "wegkomen" },
{ "en": "put on (switch on, affect)", "nl": "aandoen" },
{ "en": "take off (dismiss, deal with)", "nl": "afdoen" },
{ "en": "take part", "nl": "meedoen" },
{ "en": "imitate", "nl": "nadoen" },
{ "en": "put around (fasten)", "nl": "omdoen" },
{ "en": "gain (acquire, put on)", "nl": "opdoen" },
{ "en": "do again (hand over)", "nl": "overdoen" },
{ "en": "close (add)", "nl": "toedoen" },
{ "en": "switch off (take off)", "nl": "uitdoen" },
{ "en": "demonstrate (occur)", "nl": "voordoen" },
{ "en": "throw away (get rid of)", "nl": "wegdoen" },
{ "en": "indicate (hand over, report)", "nl": "aangeven" },
{ "en": "hand in (give off)", "nl": "afgeven" },
{ "en": "pass on", "nl": "doorgeven" },
{ "en": "give along (advise)", "nl": "meegeven" },
{ "en": "admit (yield)", "nl": "nageven" },
{ "en": "give up (submit, state)", "nl": "opgeven" },
{ "en": "hand over (vomit)", "nl": "overgeven" },
{ "en": "give back", "nl": "teruggeven" },
{ "en": "admit (concede)", "nl": "toegeven" },
{ "en": "spend (publish, issue)", "nl": "uitgeven" },
{ "en": "pretend (claim)", "nl": "voorgeven" },
{ "en": "give away", "nl": "weggeven" },
{ "en": "display (represent)", "nl": "weergeven" },
{ "en": "accept (assume, hire)", "nl": "aannemen" },
{ "en": "decrease (take away, administer)", "nl": "afnemen" },
{ "en": "review (go through)", "nl": "doornemen" },
{ "en": "take in (occupy, take medicine)", "nl": "innemen" },
{ "en": "take along", "nl": "meenemen" },
{ "en": "take over", "nl": "overnemen" },
{ "en": "record (include, answer)", "nl": "opnemen" },
{ "en": "take back", "nl": "terugnemen" },
{ "en": "increase", "nl": "toenemen" },
{ "en": "remove (take out)", "nl": "uitnemen" },
{ "en": "intend", "nl": "voornemen" },
{ "en": "observe (perceive, deputise)", "nl": "waarnemen" },
{ "en": "remove", "nl": "wegnemen" },
{ "en": "read off", "nl": "aflezen" },
{ "en": "read through", "nl": "doorlezen" },
{ "en": "read up on (import)", "nl": "inlezen" },
{ "en": "read along", "nl": "meelezen" },
{ "en": "check (proofread)", "nl": "nalezen" },
{ "en": "read aloud", "nl": "oplezen" },
{ "en": "read out (finish reading)", "nl": "uitlezen" },
{ "en": "read aloud to", "nl": "voorlezen" },
{ "en": "write to (address)", "nl": "aanschrijven" },
{ "en": "write off (copy)", "nl": "afschrijven" },
{ "en": "credit (add in writing)", "nl": "bijschrijven" },
{ "en": "register (enrol)", "nl": "inschrijven" },
{ "en": "write along (take notes)", "nl": "meeschrijven" },
{ "en": "copy", "nl": "naschrijven" },
{ "en": "write down", "nl": "opschrijven" },
{ "en": "copy (transfer)", "nl": "overschrijven" },
{ "en": "attribute", "nl": "toeschrijven" },
{ "en": "deregister (write out)", "nl": "uitschrijven" },
{ "en": "prescribe", "nl": "voorschrijven" },
{ "en": "stay behind (lag)", "nl": "achterblijven" },
{ "en": "keep up", "nl": "bijblijven" },
{ "en": "stay inside", "nl": "binnenblijven" },
{ "en": "remain", "nl": "overblijven" },
{ "en": "stay together", "nl": "samenblijven" },
{ "en": "stay home", "nl": "thuisblijven" },
{ "en": "fail to appear (be delayed)", "nl": "uitblijven" },
{ "en": "stay away", "nl": "wegblijven" },
{ "en": "hit with a vehicle (drive up)", "nl": "aanrijden" },
{ "en": "drive off (take a driving test)", "nl": "afrijden" },
{ "en": "drive in", "nl": "binnenrijden" },
{ "en": "keep driving (drive through)", "nl": "doorrijden" },
{ "en": "drive in (run in)", "nl": "inrijden" },
{ "en": "ride along", "nl": "meerijden" },
{ "en": "take a detour", "nl": "omrijden" },
{ "en": "drive up (use up)", "nl": "oprijden" },
{ "en": "run over", "nl": "overrijden" },
{ "en": "drive around", "nl": "rondrijden" },
{ "en": "drive back", "nl": "terugrijden" },
{ "en": "drive out (complete a race)", "nl": "uitrijden" },
{ "en": "get stuck (jam)", "nl": "vastrijden" },
{ "en": "pull up (drive up)", "nl": "voorrijden" },
{ "en": "drive away", "nl": "wegrijden" },
{ "en": "fly at (approach by air)", "nl": "aanvliegen" },
{ "en": "fly in", "nl": "binnenvliegen" },
{ "en": "fly on", "nl": "doorvliegen" },
{ "en": "fly in (bring by air)", "nl": "invliegen" },
{ "en": "fly along", "nl": "meevliegen" },
{ "en": "fly up (flare up)", "nl": "opvliegen" },
{ "en": "fly over", "nl": "overvliegen" },
{ "en": "fly around", "nl": "rondvliegen" },
{ "en": "fly back", "nl": "terugvliegen" },
{ "en": "fly out (leave the nest)", "nl": "uitvliegen" },
{ "en": "fly away", "nl": "wegvliegen" },
{ "en": "take place", "nl": "plaatsvinden" },
{ "en": "find again", "nl": "terugvinden" },
{ "en": "invent (find out)", "nl": "uitvinden" },
{ "en": "rediscover", "nl": "weervinden" },
{ "en": "help out", "nl": "meehelpen" },
{ "en": "help forward", "nl": "vooruithelpen" },
{ "en": "sleep through (oversleep)", "nl": "doorslapen" },
{ "en": "fall asleep", "nl": "inslapen" },
{ "en": "sleep over/along", "nl": "meeslapen" },
{ "en": "oversleep", "nl": "overslapen" },
{ "en": "sleep in", "nl": "uitslapen" },
{ "en": "attack", "nl": "aanvallen" },
{ "en": "lose weight (drop off)", "nl": "afvallen" },
{ "en": "invade (drop in)", "nl": "binnenvallen" },
{ "en": "fall through", "nl": "doorvallen" },
{ "en": "occur to (substitute, fall in)", "nl": "invallen" },
{ "en": "be better than expected", "nl": "meevallen" },
{ "en": "fall down", "nl": "neervallen" },
{ "en": "fall over", "nl": "omvallen" },
{ "en": "stand out (notice)", "nl": "opvallen" },
{ "en": "rob (overwhelm)", "nl": "overvallen" },
{ "en": "coincide", "nl": "samenvallen" },
{ "en": "disappoint", "nl": "tegenvallen" },
{ "en": "fall back (relapse)", "nl": "terugvallen" },
{ "en": "fail (drop out, lash out)", "nl": "uitvallen" },
{ "en": "fall apart", "nl": "uiteenvallen" },
{ "en": "drop out (disappear)", "nl": "wegvallen" },
{ "en": "continue (arrest, keep on)", "nl": "aanhouden" },
{ "en": "keep off (dissuade)", "nl": "afhouden" },
{ "en": "keep track of (keep up)", "nl": "bijhouden" },
{ "en": "persist", "nl": "doorhouden" },
{ "en": "contain (involve, withhold)", "nl": "inhouden" },
{ "en": "stop (hold up)", "nl": "ophouden" },
{ "en": "have left", "nl": "overhouden" },
{ "en": "stop (hold back)", "nl": "tegenhouden" },
{ "en": "hold back", "nl": "terughouden" },
{ "en": "endure", "nl": "uithouden" },
{ "en": "hold on to", "nl": "vasthouden" },
{ "en": "present (pretend)", "nl": "voorhouden" },
{ "en": "keep away", "nl": "weghouden" },
{ "en": "be on (appeal to)", "nl": "aanstaan" },
{ "en": "give up (hand over)", "nl": "afstaan" },
{ "en": "assist", "nl": "bijstaan" },
{ "en": "stand inside", "nl": "binnenstaan" },
{ "en": "endure", "nl": "doorstaan" },
{ "en": "guarantee (be responsible)", "nl": "instaan" },
{ "en": "be ready", "nl": "klaarstaan" },
{ "en": "stand up (get up)", "nl": "opstaan" },
{ "en": "be open to", "nl": "openstaan" },
{ "en": "stand still (reflect on)", "nl": "stilstaan" },
{ "en": "displease (oppose)", "nl": "tegenstaan" },
{ "en": "stand trial", "nl": "terechtstaan" },
{ "en": "allow", "nl": "toestaan" },
{ "en": "be switched off (endure)", "nl": "uitstaan" },
{ "en": "be certain (be fixed)", "nl": "vaststaan" },
{ "en": "advocate (be ahead)", "nl": "voorstaan" },
{ "en": "stand in the way", "nl": "wegstaan" },
{ "en": "be after (pursue)", "nl": "achterzitten" },
{ "en": "be in (worry)", "nl": "inzitten" },
{ "en": "sit ready", "nl": "klaarzitten" },
{ "en": "go well", "nl": "meezitten" },
{ "en": "be on (wear out)", "nl": "opzitten" },
{ "en": "sit still", "nl": "stilzitten" },
{ "en": "go badly", "nl": "tegenzitten" },
{ "en": "sit out (serve)", "nl": "uitzitten" },
{ "en": "be stuck", "nl": "vastzitten" },
{ "en": "chair (preside)", "nl": "voorzitten" },
{ "en": "be behind", "nl": "achterliggen" },
{ "en": "be alongside", "nl": "bijliggen" },
{ "en": "be ready", "nl": "klaarliggen" },
{ "en": "lie open", "nl": "openliggen" },
{ "en": "be in conflict", "nl": "overhoopliggen" },
{ "en": "be before (lie ahead)", "nl": "voorliggen" },
{ "en": "be fixed (be stuck)", "nl": "vastliggen" },
{ "en": "support (adhere to)", "nl": "aanhangen" },
{ "en": "depend on (hang down)", "nl": "afhangen" },
{ "en": "hang up", "nl": "ophangen" },
{ "en": "lean over (overhang)", "nl": "overhangen" },
{ "en": "be connected", "nl": "samenhangen" },
{ "en": "hang out (act like)", "nl": "uithangen" },
{ "en": "be attached", "nl": "vasthangen" },
{ "en": "know about", "nl": "afweten" },
{ "en": "know about too", "nl": "meeweten" },
{ "en": "announce formally", "nl": "aanzeggen" },
{ "en": "cancel", "nl": "afzeggen" },
{ "en": "repeat", "nl": "nazeggen" },
{ "en": "cancel (recite, quit)", "nl": "opzeggen" },
{ "en": "promise", "nl": "toezeggen" },
{ "en": "apply for (request)", "nl": "aanvragen" },
{ "en": "wonder", "nl": "afvragen" },
{ "en": "ask further", "nl": "doorvragen" },
{ "en": "check by asking", "nl": "navragen" },
{ "en": "request (retrieve)", "nl": "opvragen" },
{ "en": "ask around", "nl": "rondvragen" },
{ "en": "ask back (reclaim)", "nl": "terugvragen" },
{ "en": "question thoroughly", "nl": "uitvragen" },
{ "en": "look at (face)", "nl": "aankijken" },
{ "en": "copy (watch to the end)", "nl": "afkijken" },
{ "en": "look inside", "nl": "binnenkijken" },
{ "en": "look through (keep watching)", "nl": "doorkijken" },
{ "en": "watch along", "nl": "meekijken" },
{ "en": "check (look after)", "nl": "nakijken" },
{ "en": "look back (care for)", "nl": "omkijken" },
{ "en": "look up (admire)", "nl": "opkijken" },
{ "en": "look around", "nl": "rondkijken" },
{ "en": "look back", "nl": "terugkijken" },
{ "en": "watch", "nl": "toekijken" },
{ "en": "watch out (look forward to)", "nl": "uitkijken" },
{ "en": "look ahead", "nl": "vooruitkijken" },
{ "en": "look away", "nl": "wegkijken" },
{ "en": "be there (be involved)", "nl": "erbij zijn" },
{ "en": "be out (have figured it out)", "nl": "eruit zijn" },
{ "en": "be back", "nl": "terug zijn" },
{ "en": "be away", "nl": "weg zijn" },
{ "en": "be wearing (have switched on)", "nl": "aanhebben" },
{ "en": "realise (see through)", "nl": "doorhebben" },
{ "en": "have with you (be lucky)", "nl": "meehebben" },
{ "en": "have left (be willing to sacrifice)", "nl": "overhebben" },
{ "en": "intend (have in mind)", "nl": "voorhebben" },
{ "en": "be able to handle", "nl": "aankunnen" },
{ "en": "be able to come along", "nl": "meekunnen" },
{ "en": "announce (invoke)", "nl": "afroepen" },
{ "en": "call in", "nl": "binnenroepen" },
{ "en": "announce (broadcast)", "nl": "omroepen" },
{ "en": "call up (summon)", "nl": "oproepen" },
{ "en": "call out to", "nl": "toeroepen" },
{ "en": "exclaim (proclaim)", "nl": "uitroepen" },
{ "en": "call back (recall)", "nl": "terugroepen" },
{ "en": "move along (adapt)", "nl": "meebewegen" },
{ "en": "move forward", "nl": "voortbewegen" },
{ "en": "offer", "nl": "aanbieden" },
{ "en": "bid up (compete)", "nl": "opbieden" },
{ "en": "make a counterbid", "nl": "tegenbieden" },
{ "en": "put forward (carry in)", "nl": "aandragen" },
{ "en": "pay (hand over, wear out)", "nl": "afdragen" },
{ "en": "contribute", "nl": "bijdragen" },
{ "en": "carry along", "nl": "meedragen" },
{ "en": "assign (dedicate)", "nl": "opdragen" },
{ "en": "transfer", "nl": "overdragen" },
{ "en": "promote (carry out)", "nl": "uitdragen" },
{ "en": "nominate (recite)", "nl": "voordragen" },
{ "en": "carry away", "nl": "wegdragen" },
{ "en": "savour afterwards", "nl": "nagenieten" },
{ "en": "choose (select)", "nl": "uitkiezen" },
{ "en": "resonate (be audible)", "nl": "doorklinken" },
{ "en": "sound along", "nl": "meeklinken" },
{ "en": "reverberate", "nl": "naklinken" },
{ "en": "sound out (rise)", "nl": "opklinken" },
{ "en": "get inside (receive)", "nl": "binnenkrijgen" },
{ "en": "realise (get through)", "nl": "doorkrijgen" },
{ "en": "receive (understand, take along)", "nl": "meekrijgen" },
{ "en": "get back", "nl": "terugkrijgen" },
{ "en": "recommend", "nl": "aanraden" },
{ "en": "advise against", "nl": "afraden" },
{ "en": "separate (secrete)", "nl": "afscheiden" },
{ "en": "stop (excrete)", "nl": "uitscheiden" },
{ "en": "shine through", "nl": "doorschijnen" },
{ "en": "connect (join)", "nl": "aansluiten" },
{ "en": "close (conclude, disconnect)", "nl": "afsluiten" },
{ "en": "lock in", "nl": "binnensluiten" },
{ "en": "exclude (lock out)", "nl": "buitensluiten" },
{ "en": "enclose (include)", "nl": "insluiten" },
{ "en": "lock up", "nl": "opsluiten" },
{ "en": "exclude (rule out)", "nl": "uitsluiten" },
{ "en": "cut into (raise a topic)", "nl": "aansnijden" },
{ "en": "cut off", "nl": "afsnijden" },
{ "en": "trim", "nl": "bijsnijden" },
{ "en": "cut through", "nl": "doorsnijden" },
{ "en": "incise", "nl": "insnijden" },
{ "en": "slice up (boast)", "nl": "opsnijden" },
{ "en": "cut out", "nl": "uitsnijden" },
{ "en": "pre-slice (carve)", "nl": "voorsnijden" },
{ "en": "cut away", "nl": "wegsnijden" },
{ "en": "address (appeal to)", "nl": "aanspreken" },
{ "en": "arrange (agree)", "nl": "afspreken" },
{ "en": "discuss thoroughly", "nl": "doorspreken" },
{ "en": "record (speak into)", "nl": "inspreken" },
{ "en": "have a say", "nl": "meespreken" },
{ "en": "contradict", "nl": "tegenspreken" },
{ "en": "address (speak to)", "nl": "toespreken" },
{ "en": "pronounce (express)", "nl": "uitspreken" },
{ "en": "die off", "nl": "afsterven" },
{ "en": "become extinct", "nl": "uitsterven" },
{ "en": "fade away", "nl": "wegsterven" },
{ "en": "put on (attract)", "nl": "aantrekken" },
{ "en": "subtract (pull off)", "nl": "aftrekken" },
{ "en": "pull/enter inside", "nl": "binnentrekken" },
{ "en": "pull through (continue)", "nl": "doortrekken" },
{ "en": "withdraw (move in)", "nl": "intrekken" },
{ "en": "drag along", "nl": "meetrekken" },
{ "en": "check (trace)", "nl": "natrekken" },
{ "en": "pull around (encircle)", "nl": "omtrekken" },
{ "en": "pull up (accelerate, associate)", "nl": "optrekken" },
{ "en": "pull over (cover, redraw)", "nl": "overtrekken" },
{ "en": "contract (bring together)", "nl": "samentrekken" },
{ "en": "withdraw", "nl": "terugtrekken" },
{ "en": "take off (pull out)", "nl": "uittrekken" },
{ "en": "move onward", "nl": "voorttrekken" },
{ "en": "leave (pull away)", "nl": "wegtrekken" },
{ "en": "collide with (sail toward)", "nl": "aanvaren" },
{ "en": "depart by boat", "nl": "afvaren" },
{ "en": "sail in", "nl": "binnenvaren" },
{ "en": "sail on", "nl": "doorvaren" },
{ "en": "sail into", "nl": "invaren" },
{ "en": "sail along", "nl": "meevaren" },
{ "en": "sail around", "nl": "omvaren" },
{ "en": "sail across (run over by boat)", "nl": "overvaren" },
{ "en": "sail around", "nl": "rondvaren" },
{ "en": "sail back", "nl": "terugvaren" },
{ "en": "sail out", "nl": "uitvaren" },
{ "en": "sail away", "nl": "wegvaren" },
{ "en": "freeze onto", "nl": "aanvriezen" },
{ "en": "freeze shut", "nl": "dichtvriezen" },
{ "en": "freeze (freeze in)", "nl": "invriezen" },
{ "en": "freeze solid/stuck", "nl": "vastvriezen" },
{ "en": "freeze away", "nl": "wegvriezen" },
{ "en": "weigh (consider)", "nl": "afwegen" },
{ "en": "weigh in", "nl": "inwegen" },
{ "en": "weigh in (count)", "nl": "meewegen" },
{ "en": "outweigh (balance)", "nl": "opwegen" },
{ "en": "point out (appoint)", "nl": "aanwijzen" },
{ "en": "reject", "nl": "afwijzen" },
{ "en": "allocate (assign)", "nl": "toewijzen" },
{ "en": "show (expel)", "nl": "uitwijzen" },
{ "en": "point ahead", "nl": "vooruitwijzen" },
{ "en": "warm up singing (sing in)", "nl": "inzingen" },
{ "en": "sing along", "nl": "meezingen" },
{ "en": "sing after (echo)", "nl": "nazingen" },
{ "en": "sing to", "nl": "toezingen" },
{ "en": "finish singing (sing out)", "nl": "uitzingen" },
{ "en": "sing for someone", "nl": "voorzingen" },
{ "en": "deliver to the home", "nl": "thuisbezorgen" },
{ "en": "deliver around", "nl": "rondbezorgen" },
{ "en": "put on quickly (shoot at, approach)", "nl": "aanschieten" },
{ "en": "shoot down (fire)", "nl": "afschieten" },
{ "en": "rush/shoot inside", "nl": "binnenschieten" },
{ "en": "shoot through (go too far)", "nl": "doorschieten" },
{ "en": "shoot in (practise)", "nl": "inschieten" },
{ "en": "shoot along", "nl": "meeschieten" },
{ "en": "shoot down", "nl": "neerschieten" },
{ "en": "hurry up (make progress)", "nl": "opschieten" },
{ "en": "remain (shoot over)", "nl": "overschieten" },
{ "en": "hit the target", "nl": "raakschieten" },
{ "en": "rush over (shoot toward)", "nl": "toeschieten" },
{ "en": "shoot out (slip)", "nl": "uitschieten" },
{ "en": "advance money (shoot ahead)", "nl": "voorschieten" },
{ "en": "shoot away", "nl": "wegschieten" },
{ "en": "squeeze shut", "nl": "dichtknijpen" },
{ "en": "crush", "nl": "fijnknijpen" },
{ "en": "squeeze together", "nl": "samenknijpen" },
{ "en": "squeeze out (exploit)", "nl": "uitknijpen" },
{ "en": "tow away", "nl": "afslepen" },
{ "en": "drag in (secure)", "nl": "binnenslepen" },
{ "en": "drag along", "nl": "meeslepen" },
{ "en": "drag on", "nl": "voortslepen" },
{ "en": "drag away", "nl": "wegslepen" },
{ "en": "attach (add)", "nl": "bijvoegen" },
{ "en": "insert (merge into traffic)", "nl": "invoegen" },
{ "en": "merge", "nl": "samenvoegen" },
{ "en": "add", "nl": "toevoegen" },
{ "en": "listen to", "nl": "aanhoren" },
{ "en": "interrogate (test orally)", "nl": "afhoren" },
{ "en": "belong with", "nl": "bijhoren" },
{ "en": "belong", "nl": "thuishoren" },
{ "en": "rent exclusively", "nl": "afhuren" },
{ "en": "rent extra", "nl": "bijhuren" },
{ "en": "hire", "nl": "inhuren" },
{ "en": "sublet", "nl": "onderhuren" },
{ "en": "begin (tackle)", "nl": "aanvatten" },
{ "en": "interpret (pick up)", "nl": "opvatten" },
{ "en": "summarise", "nl": "samenvatten" },
{ "en": "descend (sag, drop by)", "nl": "afzakken" },
{ "en": "collapse (continue drinking)", "nl": "doorzakken" },
{ "en": "collapse (subside)", "nl": "inzakken" },
{ "en": "sag (sink down)", "nl": "uitzakken" },
{ "en": "sink away (fade)", "nl": "wegzakken" },
{ "en": "hurl away", "nl": "wegslingeren" },
{ "en": "quote (tighten, bring up)", "nl": "aanhalen" },
{ "en": "pick up (remove)", "nl": "afhalen" },
{ "en": "bring in (secure)", "nl": "binnenhalen" },
{ "en": "cross out (pull through)", "nl": "doorhalen" },
{ "en": "overtake (catch up, make up)", "nl": "inhalen" },
{ "en": "bring down", "nl": "neerhalen" },
{ "en": "pull down (persuade)", "nl": "omhalen" },
{ "en": "pick up (retrieve)", "nl": "ophalen" },
{ "en": "persuade (pull over)", "nl": "overhalen" },
{ "en": "bring back (recall)", "nl": "terughalen" },
{ "en": "lash out (pull out)", "nl": "uithalen" },
{ "en": "remove (take away)", "nl": "weghalen" },
{ "en": "flare up", "nl": "oplaaien" },
{ "en": "chew thoroughly (dwell on)", "nl": "doorkauwen" },
{ "en": "chew finely", "nl": "fijnkauwen" },
{ "en": "collide with (run up against)", "nl": "opbotsen" },
{ "en": "collide", "nl": "samenbotsen" },
{ "en": "finish with carpentry (board off)", "nl": "aftimmeren" },
{ "en": "board up", "nl": "dichttimmeren" },
{ "en": "nail down", "nl": "vasttimmeren" },
{ "en": "bend away (deflect)", "nl": "afbuigen" },
{ "en": "bend through (sag)", "nl": "doorbuigen" },
{ "en": "bend along (adapt)", "nl": "meebuigen" },
{ "en": "bend (redirect)", "nl": "ombuigen" },
{ "en": "bend back", "nl": "terugbuigen" },
{ "en": "sink (lower)", "nl": "afzinken" },
{ "en": "sink further", "nl": "doorzinken" },
{ "en": "sink away", "nl": "wegzinken" },
{ "en": "cultivate (develop)", "nl": "aankweken" },
{ "en": "raise (cultivate)", "nl": "opkweken" },
{ "en": "lean on", "nl": "opsteunen" },
{ "en": "throw shut (fill in)", "nl": "dichtgooien" },
{ "en": "knock over (overhaul)", "nl": "omgooien" },
{ "en": "throw up (raise)", "nl": "opgooien" },
{ "en": "throw across", "nl": "overgooien" },
{ "en": "throw together (pool)", "nl": "samengooien" },
{ "en": "throw out (cast out)", "nl": "uitgooien" },
{ "en": "throw away", "nl": "weggooien" },
{ "en": "touch", "nl": "aanraken" },
{ "en": "get rid of (finish)", "nl": "afgeraken" },
{ "en": "lose", "nl": "kwijtraken" },
{ "en": "come loose", "nl": "losraken" },
{ "en": "manage to come along", "nl": "meegeraken" },
{ "en": "run out", "nl": "opraken" },
{ "en": "get lost", "nl": "zoekraken" }
]

