const verbs = [
  {
    "en": "to work",
    "type": "regular",
    "Infinitief\nMeervoud": "werken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "werk",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "werkt",
    "Onvoltooid verleden tijd enkelvoud": "werkte",
    "Onvoltooid verleden tijd meervoud": "werkten",
    "Voltooid deelwoord": "heeft gewerkt",
    "Tegenwoordig deelwoord": "werkend"
  },
  {
    "en": "to make",
    "type": "regular",
    "Infinitief\nMeervoud": "maken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "maak",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "maakt",
    "Onvoltooid verleden tijd enkelvoud": "maakte",
    "Onvoltooid verleden tijd meervoud": "maakten",
    "Voltooid deelwoord": "heeft gemaakt",
    "Tegenwoordig deelwoord": "makend"
  },
  {
    "en": "to live (reside)",
    "type": "regular",
    "Infinitief\nMeervoud": "wonen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "woon",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "woont",
    "Onvoltooid verleden tijd enkelvoud": "woonde",
    "Onvoltooid verleden tijd meervoud": "woonden",
    "Voltooid deelwoord": "heeft gewoond",
    "Tegenwoordig deelwoord": "wonend"
  },
  {
    "en": "to learn",
    "type": "regular",
    "Infinitief\nMeervoud": "leren",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "leer",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "leert",
    "Onvoltooid verleden tijd enkelvoud": "leerde",
    "Onvoltooid verleden tijd meervoud": "leerden",
    "Voltooid deelwoord": "heeft geleerd",
    "Tegenwoordig deelwoord": "lerend"
  },
  {
    "en": "to play",
    "type": "regular",
    "Infinitief\nMeervoud": "spelen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "speel",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "speelt",
    "Onvoltooid verleden tijd enkelvoud": "speelde",
    "Onvoltooid verleden tijd meervoud": "speelden",
    "Voltooid deelwoord": "heeft gespeeld",
    "Tegenwoordig deelwoord": "spelend"
  },
  {
    "en": "to talk",
    "type": "regular",
    "Infinitief\nMeervoud": "praten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "praat",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "praat",
    "Onvoltooid verleden tijd enkelvoud": "praatte",
    "Onvoltooid verleden tijd meervoud": "praatten",
    "Voltooid deelwoord": "heeft gepraat",
    "Tegenwoordig deelwoord": "pratend"
  },
  {
    "en": "to listen",
    "type": "regular",
    "Infinitief\nMeervoud": "luisteren",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "luister",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "luisters",
    "Onvoltooid verleden tijd enkelvoud": "luisterde",
    "Onvoltooid verleden tijd meervoud": "luisterden",
    "Voltooid deelwoord": "heeft geluisterd",
    "Tegenwoordig deelwoord": "luisterend"
  },
  {
    "en": "to cycle",
    "type": "regular",
    "Infinitief\nMeervoud": "fietsen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "fiets",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "fietst",
    "Onvoltooid verleden tijd enkelvoud": "fietste",
    "Onvoltooid verleden tijd meervoud": "fietsten",
    "Voltooid deelwoord": "heeft gefietst",
    "Tegenwoordig deelwoord": "fietsend"
  },
  {
    "en": "to travel",
    "type": "regular",
    "Infinitief\nMeervoud": "reizen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "reis",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "reist",
    "Onvoltooid verleden tijd enkelvoud": "reisde",
    "Onvoltooid verleden tijd meervoud": "reisden",
    "Voltooid deelwoord": "heeft gereisd",
    "Tegenwoordig deelwoord": "reizend"
  },
  {
    "en": "to study",
    "type": "regular",
    "Infinitief\nMeervoud": "studeren",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "studeer",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "studeert",
    "Onvoltooid verleden tijd enkelvoud": "studeerde",
    "Onvoltooid verleden tijd meervoud": "studeerden",
    "Voltooid deelwoord": "heeft gestudeerd",
    "Tegenwoordig deelwoord": "studerend"
  },
  {
    "en": "to open",
    "type": "regular",
    "Infinitief\nMeervoud": "openen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "open",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "opent",
    "Onvoltooid verleden tijd enkelvoud": "opende",
    "Onvoltooid verleden tijd meervoud": "openden",
    "Voltooid deelwoord": "heeft geopend",
    "Tegenwoordig deelwoord": "openend"
  },
  {
    "en": "to close (shut)",
    "type": "regular",
    "Infinitief\nMeervoud": "dichten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "dicht",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "dicht",
    "Onvoltooid verleden tijd enkelvoud": "dichtte",
    "Onvoltooid verleden tijd meervoud": "dichtten",
    "Voltooid deelwoord": "heeft gedicht",
    "Tegenwoordig deelwoord": "dichtend"
  },
  {
    "en": "to cook",
    "type": "regular",
    "Infinitief\nMeervoud": "koken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "kook",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "kookt",
    "Onvoltooid verleden tijd enkelvoud": "kookte",
    "Onvoltooid verleden tijd meervoud": "kookten",
    "Voltooid deelwoord": "heeft gekookt",
    "Tegenwoordig deelwoord": "kokend"
  },
  {
    "en": "to clean",
    "type": "regular",
    "Infinitief\nMeervoud": "schoonmaken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "maak schoon",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "maakt schoon",
    "Onvoltooid verleden tijd enkelvoud": "maakte schoon",
    "Onvoltooid verleden tijd meervoud": "maakten schoon",
    "Voltooid deelwoord": "heeft schoongemaakt",
    "Tegenwoordig deelwoord": "schoonmakend"
  },
  {
    "en": "to move (house)",
    "type": "regular",
    "Infinitief\nMeervoud": "verhuizen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "verhuis",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "verhuist",
    "Onvoltooid verleden tijd enkelvoud": "verhuisde",
    "Onvoltooid verleden tijd meervoud": "verhuisden",
    "Voltooid deelwoord": "is verhuisd",
    "Tegenwoordig deelwoord": "verhuizend"
  },
  {
    "en": "to laugh",
    "type": "irregular",
    "Infinitief\nMeervoud": "lachen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "lach",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "lacht",
    "Onvoltooid verleden tijd enkelvoud": "lachte",
    "Onvoltooid verleden tijd meervoud": "lachten",
    "Voltooid deelwoord": "heeft gelachen",
    "Tegenwoordig deelwoord": "lachend"
  },
  {
    "en": "to wash",
    "type": "irregular",
    "Infinitief\nMeervoud": "wassen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "was",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "wast",
    "Onvoltooid verleden tijd enkelvoud": "waste",
    "Onvoltooid verleden tijd meervoud": "wasten",
    "Voltooid deelwoord": "heeft gewassen",
    "Tegenwoordig deelwoord": "wassend"
  },
  {
    "en": "to be called",
    "type": "irregular",
    "Infinitief\nMeervoud": "heten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "heet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "heet",
    "Onvoltooid verleden tijd enkelvoud": "heette",
    "Onvoltooid verleden tijd meervoud": "heetten",
    "Voltooid deelwoord": "heeft geheten",
    "Tegenwoordig deelwoord": "hetend"
  },
  {
    "en": "to bake",
    "type": "irregular",
    "Infinitief\nMeervoud": "bakken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "bak",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "bakt",
    "Onvoltooid verleden tijd enkelvoud": "bakte",
    "Onvoltooid verleden tijd meervoud": "bakten",
    "Voltooid deelwoord": "heeft gebakken",
    "Tegenwoordig deelwoord": "bakkend"
  },
  {
    "en": "to walk",
    "type": "irregular",
    "Infinitief\nMeervoud": "lopen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "loop",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "loopt",
    "Onvoltooid verleden tijd enkelvoud": "liep",
    "Onvoltooid verleden tijd meervoud": "liepen",
    "Voltooid deelwoord": "heeft gelopen",
    "Tegenwoordig deelwoord": "lopend"
  },
  {
    "en": "to buy",
    "type": "irregular",
    "Infinitief\nMeervoud": "kopen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "koop",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "koopt",
    "Onvoltooid verleden tijd enkelvoud": "kocht",
    "Onvoltooid verleden tijd meervoud": "kochten",
    "Voltooid deelwoord": "heeft gekocht",
    "Tegenwoordig deelwoord": "kopend"
  },
  {
    "en": "to think",
    "type": "irregular",
    "Infinitief\nMeervoud": "denken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "denk",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "denkt",
    "Onvoltooid verleden tijd enkelvoud": "dacht",
    "Onvoltooid verleden tijd meervoud": "dachten",
    "Voltooid deelwoord": "heeft gedacht",
    "Tegenwoordig deelwoord": "denkend"
  },
  {
    "en": "to bring",
    "type": "irregular",
    "Infinitief\nMeervoud": "brengen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "breng",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "brengt",
    "Onvoltooid verleden tijd enkelvoud": "bracht",
    "Onvoltooid verleden tijd meervoud": "brachten",
    "Voltooid deelwoord": "heeft gebracht",
    "Tegenwoordig deelwoord": "brengend"
  },
  {
    "en": "to search",
    "type": "irregular",
    "Infinitief\nMeervoud": "zoeken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zoek",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zoekt",
    "Onvoltooid verleden tijd enkelvoud": "zocht",
    "Onvoltooid verleden tijd meervoud": "zochten",
    "Voltooid deelwoord": "heeft gezocht",
    "Tegenwoordig deelwoord": "zoekend"
  },
  {
    "en": "to eat",
    "type": "irregular",
    "Infinitief\nMeervoud": "eten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "eet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "eet",
    "Onvoltooid verleden tijd enkelvoud": "at",
    "Onvoltooid verleden tijd meervoud": "aten",
    "Voltooid deelwoord": "heeft gegeten",
    "Tegenwoordig deelwoord": "etend"
  },
  {
    "en": "to drink",
    "type": "irregular",
    "Infinitief\nMeervoud": "drinken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "drink",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "drinkt",
    "Onvoltooid verleden tijd enkelvoud": "dronk",
    "Onvoltooid verleden tijd meervoud": "dronken",
    "Voltooid deelwoord": "heeft gedronken",
    "Tegenwoordig deelwoord": "drinkend"
  },
  {
    "en": "to see",
    "type": "irregular",
    "Infinitief\nMeervoud": "zien",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zie",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "ziet",
    "Onvoltooid verleden tijd enkelvoud": "zag",
    "Onvoltooid verleden tijd meervoud": "zagen",
    "Voltooid deelwoord": "heeft gezien",
    "Tegenwoordig deelwoord": "ziend"
  },
  {
    "en": "to go",
    "type": "irregular",
    "Infinitief\nMeervoud": "gaan",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "ga",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "gaat",
    "Onvoltooid verleden tijd enkelvoud": "ging",
    "Onvoltooid verleden tijd meervoud": "gingen",
    "Voltooid deelwoord": "is gegaan",
    "Tegenwoordig deelwoord": "gaand"
  },
  {
    "en": "to come",
    "type": "irregular",
    "Infinitief\nMeervoud": "komen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "kom",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "komt",
    "Onvoltooid verleden tijd enkelvoud": "kwam",
    "Onvoltooid verleden tijd meervoud": "kwamen",
    "Voltooid deelwoord": "is gekomen",
    "Tegenwoordig deelwoord": "komend"
  },
  {
    "en": "to do",
    "type": "irregular",
    "Infinitief\nMeervoud": "doen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "doe",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "doet",
    "Onvoltooid verleden tijd enkelvoud": "deed",
    "Onvoltooid verleden tijd meervoud": "deden",
    "Voltooid deelwoord": "heeft gedaan",
    "Tegenwoordig deelwoord": "doend"
  },
  {
    "en": "to give",
    "type": "irregular",
    "Infinitief\nMeervoud": "geven",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "geef",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "geeft",
    "Onvoltooid verleden tijd enkelvoud": "gaf",
    "Onvoltooid verleden tijd meervoud": "gaven",
    "Voltooid deelwoord": "heeft gegeven",
    "Tegenwoordig deelwoord": "gevend"
  },
  {
    "en": "to take",
    "type": "irregular",
    "Infinitief\nMeervoud": "nemen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "neem",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "neemt",
    "Onvoltooid verleden tijd enkelvoud": "nam",
    "Onvoltooid verleden tijd meervoud": "namen",
    "Voltooid deelwoord": "heeft genomen",
    "Tegenwoordig deelwoord": "nemend"
  },
  {
    "en": "to read",
    "type": "irregular",
    "Infinitief\nMeervoud": "lezen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "lees",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "leest",
    "Onvoltooid verleden tijd enkelvoud": "las",
    "Onvoltooid verleden tijd meervoud": "lazen",
    "Voltooid deelwoord": "heeft gelezen",
    "Tegenwoordig deelwoord": "lezend"
  },
  {
    "en": "to write",
    "type": "irregular",
    "Infinitief\nMeervoud": "schrijven",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "schrijf",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "schrijft",
    "Onvoltooid verleden tijd enkelvoud": "schreef",
    "Onvoltooid verleden tijd meervoud": "schreven",
    "Voltooid deelwoord": "heeft geschreven",
    "Tegenwoordig deelwoord": "schrijvend"
  },
  {
    "en": "to stay (remain)",
    "type": "irregular",
    "Infinitief\nMeervoud": "blijven",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "blijf",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "blijft",
    "Onvoltooid verleden tijd enkelvoud": "bleef",
    "Onvoltooid verleden tijd meervoud": "bleven",
    "Voltooid deelwoord": "is gebleven",
    "Tegenwoordig deelwoord": "blijvend"
  },
  {
    "en": "to ride/drive",
    "type": "irregular",
    "Infinitief\nMeervoud": "rijden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "rijd",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "rijdt",
    "Onvoltooid verleden tijd enkelvoud": "reed",
    "Onvoltooid verleden tijd meervoud": "reden",
    "Voltooid deelwoord": "is gereden",
    "Tegenwoordig deelwoord": "rijdend"
  },
  {
    "en": "to fly",
    "type": "irregular",
    "Infinitief\nMeervoud": "vliegen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vlieg",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vliegt",
    "Onvoltooid verleden tijd enkelvoud": "vloog",
    "Onvoltooid verleden tijd meervoud": "vlogen",
    "Voltooid deelwoord": "is gevlogen",
    "Tegenwoordig deelwoord": "vliegend"
  },
  {
    "en": "to find",
    "type": "irregular",
    "Infinitief\nMeervoud": "vinden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vind",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vindt",
    "Onvoltooid verleden tijd enkelvoud": "vond",
    "Onvoltooid verleden tijd meervoud": "vonden",
    "Voltooid deelwoord": "heeft gevonden",
    "Tegenwoordig deelwoord": "vindend"
  },
  {
    "en": "to begin",
    "type": "irregular",
    "Infinitief\nMeervoud": "beginnen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "begin",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "begint",
    "Onvoltooid verleden tijd enkelvoud": "begon",
    "Onvoltooid verleden tijd meervoud": "begonnen",
    "Voltooid deelwoord": "is begonnen",
    "Tegenwoordig deelwoord": "beginnend"
  },
  {
    "en": "to help",
    "type": "irregular",
    "Infinitief\nMeervoud": "helpen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "help",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "helpt",
    "Onvoltooid verleden tijd enkelvoud": "hielp",
    "Onvoltooid verleden tijd meervoud": "hielpen",
    "Voltooid deelwoord": "heeft gehelpen",
    "Tegenwoordig deelwoord": "helpend"
  },
  {
    "en": "to sleep",
    "type": "irregular",
    "Infinitief\nMeervoud": "slapen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "slaap",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "slaapt",
    "Onvoltooid verleden tijd enkelvoud": "sliep",
    "Onvoltooid verleden tijd meervoud": "sliepen",
    "Voltooid deelwoord": "heeft geslapen",
    "Tegenwoordig deelwoord": "slapend"
  },
  {
    "en": "to fall",
    "type": "irregular",
    "Infinitief\nMeervoud": "vallen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "val",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "valt",
    "Onvoltooid verleden tijd enkelvoud": "viel",
    "Onvoltooid verleden tijd meervoud": "vielen",
    "Voltooid deelwoord": "is gevallen",
    "Tegenwoordig deelwoord": "vallend"
  },
  {
    "en": "to hold (to like)",
    "type": "irregular",
    "Infinitief\nMeervoud": "houden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "houd",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "houdt",
    "Onvoltooid verleden tijd enkelvoud": "hield",
    "Onvoltooid verleden tijd meervoud": "hielden",
    "Voltooid deelwoord": "heeft gehouden",
    "Tegenwoordig deelwoord": "houdend"
  },
  {
    "en": "to stand",
    "type": "irregular",
    "Infinitief\nMeervoud": "staan",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "sta",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "staat",
    "Onvoltooid verleden tijd enkelvoud": "stond",
    "Onvoltooid verleden tijd meervoud": "stonden",
    "Voltooid deelwoord": "heeft gestaan",
    "Tegenwoordig deelwoord": "staand"
  },
  {
    "en": "to sit",
    "type": "irregular",
    "Infinitief\nMeervoud": "zitten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zit",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zit",
    "Onvoltooid verleden tijd enkelvoud": "zat",
    "Onvoltooid verleden tijd meervoud": "zaten",
    "Voltooid deelwoord": "heeft gezeten",
    "Tegenwoordig deelwoord": "zittend"
  },
  {
    "en": "to lie (recline)",
    "type": "irregular",
    "Infinitief\nMeervoud": "liggen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "lig",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "ligt",
    "Onvoltooid verleden tijd enkelvoud": "lag",
    "Onvoltooid verleden tijd meervoud": "lagen",
    "Voltooid deelwoord": "heeft gelegen",
    "Tegenwoordig deelwoord": "liggend"
  },
  {
    "en": "to hang",
    "type": "irregular",
    "Infinitief\nMeervoud": "hangen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "hang",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "hangt",
    "Onvoltooid verleden tijd enkelvoud": "hing",
    "Onvoltooid verleden tijd meervoud": "hingen",
    "Voltooid deelwoord": "heeft gehangen",
    "Tegenwoordig deelwoord": "hangend"
  },
  {
    "en": "to know (a fact)",
    "type": "irregular",
    "Infinitief\nMeervoud": "weten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "weet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "weet",
    "Onvoltooid verleden tijd enkelvoud": "wist",
    "Onvoltooid verleden tijd meervoud": "wisten",
    "Voltooid deelwoord": "heeft geweten",
    "Tegenwoordig deelwoord": "wetend"
  },
  {
    "en": "to say",
    "type": "irregular",
    "Infinitief\nMeervoud": "zeggen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zeg",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zegt",
    "Onvoltooid verleden tijd enkelvoud": "zei",
    "Onvoltooid verleden tijd meervoud": "zeiden",
    "Voltooid deelwoord": "heeft gezegd",
    "Tegenwoordig deelwoord": "zeggend"
  },
  {
    "en": "to ask",
    "type": "irregular",
    "Infinitief\nMeervoud": "vragen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vraag",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vraagt",
    "Onvoltooid verleden tijd enkelvoud": "vroeg",
    "Onvoltooid verleden tijd meervoud": "vroegen",
    "Voltooid deelwoord": "heeft gevraagd",
    "Tegenwoordig deelwoord": "vragend"
  },
  {
    "en": "to understand",
    "type": "irregular",
    "Infinitief\nMeervoud": "begrijpen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "begrijp",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "begrijpt",
    "Onvoltooid verleden tijd enkelvoud": "begreep",
    "Onvoltooid verleden tijd meervoud": "begrepen",
    "Voltooid deelwoord": "heeft begrepen",
    "Tegenwoordig deelwoord": "begrijpend"
  },
  {
    "en": "to look (watch)",
    "type": "irregular",
    "Infinitief\nMeervoud": "kijken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "kijk",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "kijkt",
    "Onvoltooid verleden tijd enkelvoud": "keek",
    "Onvoltooid verleden tijd meervoud": "keken",
    "Voltooid deelwoord": "heeft geketen",
    "Tegenwoordig deelwoord": "kijkend"
  },
  {
    "en": "to be",
    "type": "irregular",
    "Infinitief\nMeervoud": "zijn",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "ben",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "bent\nis",
    "Onvoltooid verleden tijd enkelvoud": "was",
    "Onvoltooid verleden tijd meervoud": "waren",
    "Voltooid deelwoord": "is geweest",
    "Tegenwoordig deelwoord": "zijnd"
  },
  {
    "en": "to have",
    "type": "irregular",
    "Infinitief\nMeervoud": "hebben",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "heb",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "hebt\nheeft",
    "Onvoltooid verleden tijd enkelvoud": "had",
    "Onvoltooid verleden tijd meervoud": "hadden",
    "Voltooid deelwoord": "heeft gehad",
    "Tegenwoordig deelwoord": "hebbend"
  },
  {
    "en": "to become",
    "type": "irregular",
    "Infinitief\nMeervoud": "worden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "word",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "wordt",
    "Onvoltooid verleden tijd enkelvoud": "werd",
    "Onvoltooid verleden tijd meervoud": "werden",
    "Voltooid deelwoord": "is geworden",
    "Tegenwoordig deelwoord": "wordend"
  },
  {
    "en": "can (to be able to)",
    "type": "irregular",
    "Infinitief\nMeervoud": "kunnen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "kan",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "kan / kunt\nkan",
    "Onvoltooid verleden tijd enkelvoud": "kon",
    "Onvoltooid verleden tijd meervoud": "konden",
    "Voltooid deelwoord": "heeft gekund",
    "Tegenwoordig deelwoord": "kunnend"
  },
  {
    "en": "must (to have to)",
    "type": "irregular",
    "Infinitief\nMeervoud": "moeten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "moet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "moet",
    "Onvoltooid verleden tijd enkelvoud": "moest",
    "Onvoltooid verleden tijd meervoud": "moesten",
    "Voltooid deelwoord": "heeft gemoeten",
    "Tegenwoordig deelwoord": "moetend"
  },
  {
    "en": "to want",
    "type": "irregular",
    "Infinitief\nMeervoud": "willen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "wil",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "wil / wilt\nwil",
    "Onvoltooid verleden tijd enkelvoud": "wilde / wou",
    "Onvoltooid verleden tijd meervoud": "wilden",
    "Voltooid deelwoord": "heeft gewild",
    "Tegenwoordig deelwoord": "willend"
  },
  {
    "en": "to depend",
    "type": "irregular",
    "Infinitief\nMeervoud": "afhangen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "hang af",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "hangt af",
    "Onvoltooid verleden tijd enkelvoud": "hing af",
    "Onvoltooid verleden tijd meervoud": "hingen af",
    "Voltooid deelwoord": "heeft afgehangen",
    "Tegenwoordig deelwoord": "afhangend"
  },
  {
    "en": "to exist",
    "type": "irregular",
    "Infinitief\nMeervoud": "bestaan",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "besta",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "bestaat",
    "Onvoltooid verleden tijd enkelvoud": "bestond",
    "Onvoltooid verleden tijd meervoud": "bestonden",
    "Voltooid deelwoord": "heeft bestaan",
    "Tegenwoordig deelwoord": "bestaand"
  },
  {
    "en": "to move (physically)",
    "type": "irregular",
    "Infinitief\nMeervoud": "bewegen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "beweeg",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "beweegt",
    "Onvoltooid verleden tijd enkelvoud": "bewoog",
    "Onvoltooid verleden tijd meervoud": "bewogen",
    "Voltooid deelwoord": "heeft bewogen",
    "Tegenwoordig deelwoord": "bewegend"
  },
  {
    "en": "to offer",
    "type": "irregular",
    "Infinitief\nMeervoud": "bieden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "bied",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "biedt",
    "Onvoltooid verleden tijd enkelvoud": "bood",
    "Onvoltooid verleden tijd meervoud": "boden",
    "Voltooid deelwoord": "heeft geboden",
    "Tegenwoordig deelwoord": "biedend"
  },
  {
    "en": "to appear (to turn out)",
    "type": "irregular",
    "Infinitief\nMeervoud": "blijken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "blijk",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "blijkt",
    "Onvoltooid verleden tijd enkelvoud": "bleek",
    "Onvoltooid verleden tijd meervoud": "bleken",
    "Voltooid deelwoord": "is gebleken",
    "Tegenwoordig deelwoord": "blijkend"
  },
  {
    "en": "to wear (to carry)",
    "type": "irregular",
    "Infinitief\nMeervoud": "dragen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "draag",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "draagt",
    "Onvoltooid verleden tijd enkelvoud": "droeg",
    "Onvoltooid verleden tijd meervoud": "droegen",
    "Voltooid deelwoord": "heeft gedragen",
    "Tegenwoordig deelwoord": "dragend"
  },
  {
    "en": "to enjoy",
    "type": "irregular",
    "Infinitief\nMeervoud": "genieten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "geniet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "geniet",
    "Onvoltooid verleden tijd enkelvoud": "genoot",
    "Onvoltooid verleden tijd meervoud": "genoten",
    "Voltooid deelwoord": "heeft genoten",
    "Tegenwoordig deelwoord": "genietend"
  },
  {
    "en": "to choose",
    "type": "irregular",
    "Infinitief\nMeervoud": "kiezen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "kies",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "kiest",
    "Onvoltooid verleden tijd enkelvoud": "koos",
    "Onvoltooid verleden tijd meervoud": "kozen",
    "Voltooid deelwoord": "heeft gekozen",
    "Tegenwoordig deelwoord": "kiezend"
  },
  {
    "en": "to sound",
    "type": "irregular",
    "Infinitief\nMeervoud": "klinken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "klink",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "klinkt",
    "Onvoltooid verleden tijd enkelvoud": "klonk",
    "Onvoltooid verleden tijd meervoud": "klonken",
    "Voltooid deelwoord": "heeft geklonken",
    "Tegenwoordig deelwoord": "klinkend"
  },
  {
    "en": "to get (to receive)",
    "type": "irregular",
    "Infinitief\nMeervoud": "krijgen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "krijg",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "krijgt",
    "Onvoltooid verleden tijd enkelvoud": "kreeg",
    "Onvoltooid verleden tijd meervoud": "kregen",
    "Voltooid deelwoord": "heeft gekregen",
    "Tegenwoordig deelwoord": "krijgend"
  },
  {
    "en": "to look like (to seem)",
    "type": "irregular",
    "Infinitief\nMeervoud": "lijken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "lijk",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "lijkt",
    "Onvoltooid verleden tijd enkelvoud": "leek",
    "Onvoltooid verleden tijd meervoud": "leken",
    "Voltooid deelwoord": "heeft geleken",
    "Tegenwoordig deelwoord": "lijkend"
  },
  {
    "en": "may (to be allowed to)",
    "type": "irregular",
    "Infinitief\nMeervoud": "mogen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "mag",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "mag / moogt\nmag",
    "Onvoltooid verleden tijd enkelvoud": "mocht",
    "Onvoltooid verleden tijd meervoud": "mochten",
    "Voltooid deelwoord": "heeft gemogen",
    "Tegenwoordig deelwoord": "mogend"
  },
  {
    "en": "to receive",
    "type": "irregular",
    "Infinitief\nMeervoud": "ontvangen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "ontvang",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "ontvangt",
    "Onvoltooid verleden tijd enkelvoud": "ontving",
    "Onvoltooid verleden tijd meervoud": "ontvingen",
    "Voltooid deelwoord": "heeft ontvangen",
    "Tegenwoordig deelwoord": "ontvangend"
  },
  {
    "en": "to guess (to advise)",
    "type": "irregular",
    "Infinitief\nMeervoud": "raden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "raad",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "raadt",
    "Onvoltooid verleden tijd enkelvoud": "raadde",
    "Onvoltooid verleden tijd meervoud": "raadden",
    "Voltooid deelwoord": "heeft geraden",
    "Tegenwoordig deelwoord": "radend"
  },
  {
    "en": "to separate (to divide)",
    "type": "irregular",
    "Infinitief\nMeervoud": "scheiden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "scheid",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "scheidt",
    "Onvoltooid verleden tijd enkelvoud": "scheidde",
    "Onvoltooid verleden tijd meervoud": "scheidden",
    "Voltooid deelwoord": "is gescheiden",
    "Tegenwoordig deelwoord": "scheidend"
  },
  {
    "en": "to shine (to seem)",
    "type": "irregular",
    "Infinitief\nMeervoud": "schijnen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "schijn",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "schijnt",
    "Onvoltooid verleden tijd enkelvoud": "scheen",
    "Onvoltooid verleden tijd meervoud": "schenen",
    "Voltooid deelwoord": "heeft geschenen",
    "Tegenwoordig deelwoord": "schijnend"
  },
  {
    "en": "to close (to lock)",
    "type": "irregular",
    "Infinitief\nMeervoud": "sluiten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "sluit",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "sluit",
    "Onvoltooid verleden tijd enkelvoud": "sloot",
    "Onvoltooid verleden tijd meervoud": "sloten",
    "Voltooid deelwoord": "heeft gesloten",
    "Tegenwoordig deelwoord": "sluitend"
  },
  {
    "en": "to cut",
    "type": "irregular",
    "Infinitief\nMeervoud": "snijden",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "snijd",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "snijdt",
    "Onvoltooid verleden tijd enkelvoud": "sneed",
    "Onvoltooid verleden tijd meervoud": "sneden",
    "Voltooid deelwoord": "heeft gesneden",
    "Tegenwoordig deelwoord": "snijdend"
  },
  {
    "en": "to blow one's nose",
    "type": "irregular",
    "Infinitief\nMeervoud": "snuiten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "snuit",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "snuit",
    "Onvoltooid verleden tijd enkelvoud": "snoot",
    "Onvoltooid verleden tijd meervoud": "snoten",
    "Voltooid deelwoord": "heeft gesnoten",
    "Tegenwoordig deelwoord": "snuitend"
  },
  {
    "en": "to regret (to be sorry)",
    "type": "irregular",
    "Infinitief\nMeervoud": "spijten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "spijt",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "spijt",
    "Onvoltooid verleden tijd enkelvoud": "speet",
    "Onvoltooid verleden tijd meervoud": "speten",
    "Voltooid deelwoord": "heeft gespeten",
    "Tegenwoordig deelwoord": "spijtend"
  },
  {
    "en": "to speak",
    "type": "irregular",
    "Infinitief\nMeervoud": "spreken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "spreek",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "spreekt",
    "Onvoltooid verleden tijd enkelvoud": "sprak",
    "Onvoltooid verleden tijd meervoud": "spraken",
    "Voltooid deelwoord": "heeft gesproken",
    "Tegenwoordig deelwoord": "sprekend"
  },
  {
    "en": "to steal",
    "type": "irregular",
    "Infinitief\nMeervoud": "stelen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "steel",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "steelt",
    "Onvoltooid verleden tijd enkelvoud": "stal",
    "Onvoltooid verleden tijd meervoud": "stalen",
    "Voltooid deelwoord": "heeft gestolen",
    "Tegenwoordig deelwoord": "stelend"
  },
  {
    "en": "to die",
    "type": "irregular",
    "Infinitief\nMeervoud": "sterven",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "sterf",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "sterft",
    "Onvoltooid verleden tijd enkelvoud": "stierf",
    "Onvoltooid verleden tijd meervoud": "stierven",
    "Voltooid deelwoord": "is gestorven",
    "Tegenwoordig deelwoord": "stervend"
  },
  {
    "en": "to pull (to draw)",
    "type": "irregular",
    "Infinitief\nMeervoud": "trekken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "trek",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "trekt",
    "Onvoltooid verleden tijd enkelvoud": "trok",
    "Onvoltooid verleden tijd meervoud": "trokken",
    "Voltooid deelwoord": "heeft getrokken",
    "Tegenwoordig deelwoord": "trekkend"
  },
  {
    "en": "to sail (to drive a boat)",
    "type": "irregular",
    "Infinitief\nMeervoud": "varen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vaar",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vaart",
    "Onvoltooid verleden tijd enkelvoud": "voer",
    "Onvoltooid verleden tijd meervoud": "voeren",
    "Voltooid deelwoord": "heeft/is gevaren",
    "Tegenwoordig deelwoord": "varend"
  },
  {
    "en": "to forget",
    "type": "irregular",
    "Infinitief\nMeervoud": "vergeten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vergeet",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vergeet",
    "Onvoltooid verleden tijd enkelvoud": "vergat",
    "Onvoltooid verleden tijd meervoud": "vergaten",
    "Voltooid deelwoord": "heeft/is vergeten",
    "Tegenwoordig deelwoord": "vergetend"
  },
  {
    "en": "to depart (to leave)",
    "type": "irregular",
    "Infinitief\nMeervoud": "vertrekken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vertrek",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vertrekt",
    "Onvoltooid verleden tijd enkelvoud": "vertrok",
    "Onvoltooid verleden tijd meervoud": "vertrokken",
    "Voltooid deelwoord": "is vertrokken",
    "Tegenwoordig deelwoord": "vertrekkend"
  },
  {
    "en": "to freeze",
    "type": "irregular",
    "Infinitief\nMeervoud": "vriezen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "vries",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "vriest",
    "Onvoltooid verleden tijd enkelvoud": "vroor",
    "Onvoltooid verleden tijd meervoud": "vroren",
    "Voltooid deelwoord": "heeft gevroren",
    "Tegenwoordig deelwoord": "vriezend"
  },
  {
    "en": "to weigh",
    "type": "irregular",
    "Infinitief\nMeervoud": "wegen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "weeg",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "weegt",
    "Onvoltooid verleden tijd enkelvoud": "woog",
    "Onvoltooid verleden tijd meervoud": "wogen",
    "Voltooid deelwoord": "heeft gewogen",
    "Tegenwoordig deelwoord": "wegend"
  },
  {
    "en": "to point out (to show)",
    "type": "irregular",
    "Infinitief\nMeervoud": "wijzen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "wees",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "wijst",
    "Onvoltooid verleden tijd enkelvoud": "wees",
    "Onvoltooid verleden tijd meervoud": "wezen",
    "Voltooid deelwoord": "heeft gewezen",
    "Tegenwoordig deelwoord": "wijzend"
  },
  {
    "en": "to sing",
    "type": "irregular",
    "Infinitief\nMeervoud": "zingen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zing",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zingt",
    "Onvoltooid verleden tijd enkelvoud": "zong",
    "Onvoltooid verleden tijd meervoud": "zongen",
    "Voltooid deelwoord": "heeft gezongen",
    "Tegenwoordig deelwoord": "zingend"
  },
  {
    "en": "to sit",
    "type": "irregular",
    "Infinitief\nMeervoud": "zitten",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zit",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zit",
    "Onvoltooid verleden tijd enkelvoud": "zat",
    "Onvoltooid verleden tijd meervoud": "zaten",
    "Voltooid deelwoord": "heeft gezeten",
    "Tegenwoordig deelwoord": "zittend"
  },
  {
    "en": "to search",
    "type": "irregular",
    "Infinitief\nMeervoud": "zoeken",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zoek",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zoekt",
    "Onvoltooid verleden tijd enkelvoud": "zocht",
    "Onvoltooid verleden tijd meervoud": "zochten",
    "Voltooid deelwoord": "heeft gezocht",
    "Tegenwoordig deelwoord": "zoekend"
  },
  {
    "en": "shall (will)",
    "type": "irregular",
    "Infinitief\nMeervoud": "zullen",
    "Eerste persoon enkelvoud\nTweede persoon enkelvoud met inversie informeel (e.g., een vraag)\nGebiedende wijs": "zal",
    "Tweede persoon enkelvoud\nDerde persoon enkelvoud": "zal / zult\nzal",
    "Onvoltooid verleden tijd enkelvoud": "zou",
    "Onvoltooid verleden tijd meervoud": "zouden",
    "Voltooid deelwoord": "-",
    "Tegenwoordig deelwoord": "zullend"
  }
]