const words = [
{ "en": "disrupted (disturbed, bijvoeglijk naamwoord)", "type": "adjective", "nl": "verstoord" },
{ "en": "icy", "type": "adjective", "nl": "ijzig" },
{ "en": "since (because)", "type": "conjunction", "nl": "aangezien" },
{ "en": "since (time)", "type": "conjunction", "nl": "sinds" },
{ "en": "ally", "type": "noun", "nl": "de bondgenoot" },
{ "en": "decision", "type": "noun", "nl": "het besluit" },
{ "en": "decisions", "type": "noun", "nl": "de besluiten" },
{ "en": "excluded", "type": "adjective", "nl": "uitgesloten" },
{ "en": "destroyed", "type": "adjective", "nl": "verwoest" },
{ "en": "approved", "type": "adjective", "nl": "goedgekeurd" },
{ "en": "regarding", "type": "preposition", "nl": "wat betreft" },
{ "en": "expired", "type": "adjective", "nl": "verlopen" },
{ "en": "lapsed", "type": "adjective", "nl": "vervallen (ongeldig geworden)" },
{ "en": "invalid", "type": "adjective", "nl": "ongeldig" },
{ "en": "patient (bijvoeglijk naamwoord)", "type": "adjective", "nl": "geduldig" },
{ "en": "behaviour", "type": "noun", "nl": "het gedrag" },
{ "en": "view (visibility)", "type": "noun", "nl": "het zicht" },
{ "en": "gust", "type": "noun", "nl": "de vlaag" },
{ "en": "gusts", "type": "noun", "nl": "de vlagen" },
{ "en": "dropped (descended)", "type": "adjective", "nl": "gezakt (gedaald)" },
{ "en": "sunk", "type": "adjective", "nl": "gezonken" },
{ "en": "pocket", "type": "noun", "nl": "de zak (de broekzak)" },
{ "en": "pockets", "type": "noun", "nl": "de zakken" },
{ "en": "bag", "type": "noun", "nl": "de tas (de zak)" },
{ "en": "bags", "type": "noun", "nl": "de tassen (de zakken)" },
{ "en": "business (matters or affairs)", "type": "noun", "nl": "de zaken" },
{ "en": "completely", "type": "adverb", "nl": "volkomen" },
{ "en": "to come into view", "type": "adverbial phrase", "nl": "tevoorschijn komen (De kat kwam onder het bed tevoorschijn)" },
{ "en": "to bring out (to reveal, to fetch out)", "type": "verb", "nl": "tevoorschijn halen (Hij haalde een sleutel tevoorschijn)"},
{ "en": "accident", "type": "noun", "nl": "het ongeluk (het ongeval - formeel)" },
{ "en": "accidents", "type": "noun", "nl": "de ongelukken (de ongevallen - formeel)" },
{ "en": "as a result of which", "type": "conjunction", "nl": "waardoor" },
{ "en": "grown (cultivated)", "type": "adjective", "nl": "gekweekt" },
{ "en": "complaints", "type": "noun", "nl": "de klachten" },
{ "en": "misconduct (malpractice)", "type": "noun", "nl": "de misstanden" },
{ "en": "case (situation)", "type": "noun", "nl": "het geval" },
{ "en": "cases (situations)", "type": "noun", "nl": "de gevallen" },
{ "en": "section", "type": "noun", "nl": "het gedeelte" },
{ "en": "sections", "type": "noun", "nl": "de gedeelten (de gedeeltes)" },
{ "en": "down", "type": "adverb", "nl": "neer (omlaag)" },
{ "en": "similar", "type": "adjective", "nl": "soortgelijk (vergelijkbaar)" },
{ "en": "enemy", "type": "noun", "nl": "de vijand" },
{ "en": "enemies", "type": "noun", "nl": "de vijanden" },
{ "en": "expectation", "type": "noun", "nl": "de verwachting" },
{ "en": "expectations", "type": "noun", "nl": "de verwachtingen" },
{ "en": "prepared", "type": "adjective", "nl": "voorbereid" },
{ "en": "willing", "type": "adjective", "nl": "bereid om" },
{ "en": "invitation", "type": "noun", "nl": "de uitnodiging" },
{ "en": "invitations", "type": "noun", "nl": "de uitnodigingen" },
{ "en": "to agree", "type": "verb", "nl": "overeenkomen (het eens zijn)" },
{ "en": "to match (to correspond)", "type": "verb", "nl": "overeenkomen met" },
{ "en": "shallow", "type": "adjective", "nl": "ondiep" },
{ "en": "superficial (shallow)", "type": "adjective", "nl": "oppervlakkig" },
{ "en": "to subtract", "type": "verb", "nl": "aftrekken" },
{ "en": "inference (conclusion)", "type": "noun", "nl": "de gevolgtrekking" },
{ "en": "comparable", "type": "adjective", "nl": "vergelijkbaar" },
{ "en": "literal", "type": "adjective", "nl": "letterlijk" },
{ "en": "literally", "type": "adverb", "nl": "letterlijk" },
{ "en": "actually", "type": "adverb", "nl": "eigenlijk (daadwerkelijk)" },
{ "en": "weight", "type": "noun", "nl": "het gewicht" },
{ "en": "weights", "type": "noun", "nl": "de gewichten" },
{ "en": "to owe", "type": "verb", "nl": "verschuldigd zijn" },
{ "en": "support", "type": "noun", "nl": "de steun" },
{ "en": "insult", "type": "noun", "nl": "de belediging" },
{ "en": "insults", "type": "noun", "nl": "de beledigingen" },
{ "en": "display (rendering)", "type": "noun", "nl": "de weergave" },
{ "en": "display (performance)", "type": "noun", "nl": "de voorstelling" },
{ "en": "display (ostentatious)", "type": "noun", "nl": "het vertoon (vertoning)" },
{ "en": "useless (without a purpose)", "type": "adjective", "nl": "nutteloos" },
{ "en": "useless (unusable)", "type": "adjective", "nl": "onbruikbaar"},
{ "en": "pointless", "type": "adjective", "nl": "zinloos"},
{ "en": "to use", "type": "verb", "nl": "gebruiken"},
{ "en": "to respond (react)", "type": "verb", "nl": "reageren op"},
{ "en": "issue (matter)", "type": "noun", "nl": "de kwestie" },
{ "en": "subject (topic)", "type": "noun", "nl": "het onderwerp" },
{ "en": "it is about (the point is)", "type": "phrase", "nl": "het gaat erom" },
{ "en": "about it", "type": "phrase", "nl": "erover" },
{ "en": "satisfying (satisfied)", "type": "adjective", "nl": "bevredigend" },
{ "en": "satisfied (content)", "type": "adjective", "nl": "tevreden" },
{ "en": "to long for", "type": "verb", "nl": "verlangen naar" },
{ "en": "rarely", "type": "adverb", "nl": "zelden" },
{ "en": "curious", "type": "adjective", "nl": "nieuwsgierig" },
{ "en": "barely", "type": "adverb", "nl": "nauwelijks (bijna niet)" },
{ "en": "could (verleden tijd)", "type": "verb", "nl": "kon" },
{ "en": "could (hypothetically)", "type": "verb", "nl": "zou kunnen" },
{ "en": "evil (malicious, malevolent)", "type": "adjective", "nl": "kwaadaardig" },
{ "en": "it is only a matter of time", "type": "phrase", "nl": "het is slechts een kwestie van tijd" },
{ "en": "I wonder", "type": "phrase", "nl": "ik vraag me af" },
{ "en": "another one (one more)", "type": "phrase", "nl": "nog een" },
{ "en": "reviews", "type": "noun", "nl": "de recensies" },
{ "en": "it's none of your business", "type": "phrase", "nl": "het gaat je niets aan" },
{ "en": "this dish", "type": "noun phrase", "nl": "dit gerecht" },
{ "en": "to solve", "type": "verb", "nl": "oplossen" },
{ "en": "incredible (unbelievable)", "type": "adjective", "nl": "ongelooflijk" },
{ "en": "to show something", "type": "verb phrase", "nl": "iets laten zien" },
{ "en": "hope", "type": "noun", "nl": "de hoop" },
{ "en": "a heap (a lot)", "type": "noun", "nl": "een hoop" },
{ "en": "abuse (mistreatment, especially physical)", "type": "noun", "nl": "de mishandeling" },
{ "en": "to abuse (to mistreat, especially physically)", "type": "verb", "nl": "mishandelen" },
{ "en": "to chase (physically pursue)", "type": "verb", "nl": "achtervolgen" },
{ "en": "to pursue (work towards)", "type": "verb", "nl": "nastreven" },
{ "en": "to pursue (ambitiously chase after)", "type": "verb", "nl": "najagen" },
{ "en": "you are right", "type": "phrase", "nl": "je hebt gelijk" },
{ "en": "will take a long time (will last a long time)", "type": "verb phrase", "nl": "zal lang duren" },
{ "en": "strong (substantial, considerable)", "type": "adjective", "nl": "flink" },
{ "en": "to insult", "type": "verb", "nl": "beledigen" },
{ "en": "worst", "type": "adjective", "nl": "slechtste" },
{ "en": "worse", "type": "adjective", "nl": "erger"},
{ "en": "the favour", "type": "noun phrase", "nl": "het gunst" },
{ "en": "the advantage", "type": "noun phrase", "nl": "het voordeel" },
{ "en": "to produce", "type": "verb", "nl": "produceren"  },
{ "en": "to fetch", "type": "verb", "nl": "ophalen" }
];
