const words = [
{ "en": "disturbed (bijvoeglijk naamwoord)", "type": "adjective", "nl": "verstoord" },
{ "en": "icy", "type": "adjective", "nl": "ijzig" },
{ "en": "since (because)", "type": "conjunction", "nl": "aangezien" },
{ "en": "since (time)", "type": "conjunction", "nl": "sinds" },
{ "en": "ally", "type": "noun", "nl": "de bondgenoot" },
{ "en": "conclusion (decision)", "type": "noun", "nl": "het besluit" },
{ "en": "conclusions", "type": "noun", "nl": "de besluiten" },
{ "en": "excluded", "type": "adjective", "nl": "uitgesloten" },
{ "en": "destroyed", "type": "adjective", "nl": "verwoest" },
{ "en": "approved", "type": "adjective", "nl": "goedgekeurd" },
{ "en": "regarding", "type": "preposition", "nl": "wat betreft" },
{ "en": "expired", "type": "adjective", "nl": "verlopen" },
{ "en": "lapsed", "type": "adjective", "nl": "vervallen (ongeldig geworden)" },
{ "en": "invalid", "type": "adjective", "nl": "ongeldig" },
{ "en": "patient (bijvoeglijk naamwoord)", "type": "adjective", "nl": "geduldig" },
{ "en": "behaviour", "type": "noun", "nl": "het gedrag" },
{ "en": "view (visibility)", "type": "noun", "nl": "het zicht" },
{ "en": "gust", "type": "noun", "nl": "de vlaag" },
{ "en": "gusts", "type": "noun", "nl": "de vlagen" },
{ "en": "dropped (descended)", "type": "adjective", "nl": "gezakt (gedaald)" },
{ "en": "sunk", "type": "adjective", "nl": "gezonken" },
{ "en": "pocket", "type": "noun", "nl": "de zak (de broekzak)" },
{ "en": "pockets", "type": "noun", "nl": "de zakken" },
{ "en": "bag", "type": "noun", "nl": "de tas (de zak)" },
{ "en": "bags", "type": "noun", "nl": "de tassen (de zakken)" },
{ "en": "business (matters or affairs)", "type": "noun", "nl": "de zaken" },
{ "en": "completely", "type": "adverb", "nl": "volkomen" },
{ "en": "into view", "type": "adverbial phrase", "nl": "tevoorschijn komen (De kat kwam onder het bed tevoorschijn)" },
{ "en": "to produce (to take out)", "nl": "tevoorschijn halen (Hij haalde een sleutel tevoorschijn)"},
{ "en": "accident", "type": "noun", "nl": "het ongeval (het ongeluk)" },
{ "en": "accidents", "type": "noun", "nl": "de ongevallen (de ongelukken)" },
{ "en": "as a result of which", "type": "conjunction", "nl": "waardoor" },
{ "en": "grown (cultivated)", "type": "adjective", "nl": "gekweekt" },
{ "en": "complaints", "type": "noun", "nl": "de klachten" },
{ "en": "abuses (misconduct)", "type": "noun", "nl": "de misstanden" },
{ "en": "case (situation)", "type": "noun", "nl": "het geval" },
{ "en": "cases (situations)", "type": "noun", "nl": "de gevallen" },
{ "en": "part (section)", "type": "noun", "nl": "het gedeelte" },
{ "en": "parts (sections)", "type": "noun", "nl": "de gedeelten (de gedeeltes)" },
{ "en": "down", "type": "adverb", "nl": "neer (omlaag)" },
{ "en": "similar", "type": "adjective", "nl": "soortgelijk (vergelijkbaar)" },
{ "en": "enemy", "type": "noun", "nl": "de vijand" },
{ "en": "enemies", "type": "noun", "nl": "de vijanden" },
{ "en": "expectation", "type": "noun", "nl": "de verwachting" },
{ "en": "expectations", "type": "noun", "nl": "de verwachtingen" },
{ "en": "prepared (ready)", "type": "adjective", "nl": "voorbereid (klaar)" },
{ "en": "willing", "type": "adjective", "nl": "bereid" },
{ "en": "invitation", "type": "noun", "nl": "de uitnodiging" },
{ "en": "invitations", "type": "noun", "nl": "de uitnodigingen" },
{ "en": "matching (corresponding)", "type": "adjective", "nl": "overeenkomend" },
{ "en": "shallow", "type": "adjective", "nl": "ondiep" },
{ "en": "superficial", "type": "adjective", "nl": "oppervlakkig" },
{ "en": "deduction", "type": "noun", "nl": "de aftrek" },
{ "en": "deduction (inference)", "type": "noun", "nl": "de gevolgtrekking" },
{ "en": "comparable", "type": "adjective", "nl": "vergelijkbaar" },
{ "en": "literal", "type": "adjective", "nl": "letterlijk" },
{ "en": "literally", "type": "adverb", "nl": "letterlijk" },
{ "en": "actually", "type": "adverb", "nl": "eigenlijk (daadwerkelijk)" },
{ "en": "weight", "type": "noun", "nl": "het gewicht" },
{ "en": "weights", "type": "noun", "nl": "de gewichten" },
{ "en": "owed (due)", "type": "adjective", "nl": "verschuldigd" },
{ "en": "support", "type": "noun", "nl": "de steun" },
{ "en": "insult", "type": "noun", "nl": "de belediging" },
{ "en": "insults", "type": "noun", "nl": "de beledigingen" },
{ "en": "display (presentation)", "type": "noun", "nl": "de weergave (de vertoning)" },
{ "en": "display (ostentation)", "type": "noun", "nl": "het vertoon" },
];
